### ISSUE TITLE
README needs to say how to install 

### ISSUE THREAD

**Issue by ViralBShah** [JuliaComputing/ArrayFire.jl#10]
It would be nice if the README could have instructions for installation, and also examples.

**Comment by ViralBShah** [comment]
Some basic performance numbers that show off the capabilities will also be good to have.

**Comment by ranjanan** [comment]
Sure. Will do soon.

**Comment by ViralBShah** [comment]
Seems like this can be closed?

**Comment by ranjanan** [comment]
Yeah. Will add performance charts soon.

**Comment by ViralBShah** [comment]
Would be nice to show some performance numbers and the hardware on which those were achieved.

**Comment by ranjanan** [comment]
![arrayfire](https://cloud.githubusercontent.com/assets/9101377/13040156/8f33516c-d3ce-11e5-9873-766a2ab67781.png)

**Comment by pavanky** [comment]
FYI random numbers generated on the GPU may not be comparable to those generated on CPU in Julia.

**Comment by ViralBShah** [comment]
@pavnky What does ArrayFire do for RNG?

**Comment by pavanky** [comment]
For cuda we just use curand which uses [XORWOW](http://docs.nvidia.com/cuda/curand/device-api-overview.html) by default.

**Comment by ViralBShah** [comment]
Thanks.

**Comment by ranjanan** [comment]
![ArrayFire Performance](https://cloud.githubusercontent.com/assets/9101377/14274448/019f5e4e-fb2f-11e5-8b4b-6a81b1f31a9f.png)

**Comment by ranjanan** [comment]
![thing](https://cloud.githubusercontent.com/assets/9101377/14518524/fd16799e-0235-11e6-94c3-549518d25db1.png)

**Comment by ranjanan** [comment]
<img width="537" alt="general" src="https://cloud.githubusercontent.com/assets/9101377/15921168/36b4f1fc-2e3d-11e6-871a-c8989c5bd279.png">

**Comment by ranjanan** [comment]
![nmf single](https://cloud.githubusercontent.com/assets/9101377/15921185/62ad8198-2e3d-11e6-911e-469375a99ecb.png)

**Comment by ViralBShah** [comment]
The RNG difference is worth capturing in the compute model section of the README.
