### ISSUE TITLE
ArrayFire wrapping not working on mac OS X

### ISSUE THREAD

**Issue by Foadsf** [JuliaComputing/ArrayFire.jl#101]
I installed ArrayFire using HomeBrew and then linked it. ran `Pkg.test("ArrayFire")` command and the result is: `INFO: ArrayFire tests passed` but when I'm trying to follow [the example in this page](https://github.com/JuliaComputing/ArrayFire.jl) I have the error `ERROR: UndefVarError: AFArray not defined` . I would appreciate if you could help me.

**Comment by ranjanan** [comment]
@Foadsf have you tried doing `using ArrayFire` and then running your code? Does the following example work for you:
```julia
using ArrayFire
a = rand(Float32, 10)
ad = AFArray(a)
```

**Comment by Foadsf** [comment]
now it works. sorry if I'm a noob. but the instructions in that page does not mention the step for using `using ArrayFire` :) you may consider adding it

**Comment by ranjanan** [comment]
Sure, I'll add it to my README. Thanks for the suggestion! :)
