### ISSUE TITLE
Complex128 set not working

### ISSUE THREAD

**Issue by ameresj** [JuliaComputing/ArrayFire.jl#103]
I am getting an weird error in this example, when setting complex numbers. Backend is OpenCL ArrayFire version 3.5.0.  
```
using ArrayFire
a=rand(AFArray{Float64},2)
b=rand(AFArray{Float64},2)
c=zeros(AFArray{Complex128},2)
#This works
c=a+im*b
for idx=1:2
 c[idx]=a[idx]*2.0*im
end
#This doesnt
for idx=1:2
 c[idx]=a[idx]+im*b[idx]
end
```

> indexed assignment not defined for ArrayFire.AFArray{Complex{Float64},1}
>  in setindex!(::ArrayFire.AFArray{Complex{Float64},1}, ::Complex{Float64}, ::Int64) at ./abstractarray.jl:875
>  in macro expansion; at ./console:2 [inlined]
>  in anonymous at ./<missing>:?
>  in include_string(::String, ::String) at ./loading.jl:478
>  in eval(::Module, ::Any) at ./boot.jl:236
>  in (::Atom.##67#70)() at /home/ameresj/.julia/v0.6/Atom/src/eval.jl:40
>  in withpath(::Atom.##67#70, ::Void) at /home/ameresj/.julia/v0.6/CodeTools/src/utils.jl:30
>  in withpath(::Function, ::Void) at /home/ameresj/.julia/v0.6/Atom/src/eval.jl:46
>  in macro expansion at /home/ameresj/.julia/v0.6/Atom/src/eval.jl:109 [inlined]
>  in (::Atom.##66#69)() at ./task.jl:76

**Comment by jgbos** [comment]
This error is fixed by changing  `setindex!` to the following:

```bash
-function setindex!{T,S<:Real}(lhs::AFArray{T}, val::S, idx::Union{Range,Int,Colon,AFArray}...)
+function setindex!{T,S}(lhs::AFArray{T}, val::S, idx::Union{Range,Int,Colon,AFArray}...)
```

I don't know if there was a good reason to only use `Real` numbers for this function, but all tests pass and have had no issues using complex numbers.

**Comment by ranjanan** [comment]
@jgbos Thank you for pointing this out, and apologies for getting to this late. Could you please send a PR with this fix? I would appreciate it.

**Comment by ranjanan** [comment]
Actually I'll do it myself this time, but it'd be great if you guys can submit PRs (after filing issues) so I can review them and merge them as appropriate
