### ISSUE TITLE
Array versions of exp, sin, etc. are deprecated in v0.6 Base

### ISSUE THREAD

**Issue by gaika** [JuliaComputing/ArrayFire.jl#104]
What is the proper way to write portable code since the array versions of math functions got deprecated in v0.6? Is it even possible to support broadcast fusion in statements like exp.(sin.(x))?

**Comment by gaika** [comment]
Is it possible to map Julia's `broadcast` and `broadcast!` to ArrayFire's `gfor`?

**Comment by ViralBShah** [comment]
It ought to be possible, I think.

**Comment by pavanky** [comment]
FYI this is what we I ended up doing in python as an alternative to GFOR:

- http://arrayfire.org/arrayfire-python/_modules/arrayfire/bcast.html#broadcast
- http://arrayfire.org/arrayfire-python/_modules/arrayfire/index.html#ParallelRange

**Comment by gaika** [comment]
I'm just trying to make [automatic differentiation](https://github.com/gaika/AutoDiffSource.jl) work with ArrayFire. After type stability fixes in #93  basic math operations now work fine, but lack of `broadcast()` support is a showstopper for all other functions.

**Comment by ranjanan** [comment]
I think for v0.6 I can define the appropriate broadcast functions. However, I don't think there would be any benefits from the fusion operations at the Julia wrapper level. ArrayFire's JIT would perform those fusions internally 

>ArrayFire features an intelligent Just-In-Time (JIT) compilation engine that converts expressions using arrays into the smallest number of CUDA/OpenCL kernels ... This "kernel fusion" technology not only decreases the number of kernel calls, but, more importantly, avoids extraneous global memory operations.

**Comment by ViralBShah** [comment]
@ranjanan How difficult is it to support broadcast for the 0.6-dev without breaking 0.5. Let's do it if we can. But if it is tedious, let's wait for 0.6.

**Comment by ranjanan** [comment]
The simplest way to address this is to simply define for versions greater than v0.5: 
```julia
Base.broadcast{T}(f::Function, a::AFArray{T}) = f(a)
```
This would support the `.` syntax, but still leaves all the kernel fusion to the ArrayFire library. So the `exp.(sin.(x))` syntax would be the same as `exp(sin(x))`, while ArrayFire's JIT  fuses the `exp` and the `sin`. 

I shall send a PR with this patch soon.
