### ISSUE TITLE
sign() in arrayfire is different from julia

### ISSUE THREAD

**Issue by gaika** [JuliaComputing/ArrayFire.jl#109]
In ArrayFire sign() gives "output is 1 for negative numbers and 0 for positive numbers" while in julia it is "Return zero if x==0 and x/|x| otherwise (i.e., ±1 for real x)."

**Comment by pavanky** [comment]
Hmm in retrospect, arrayfire should have called it `signbit`. The definition of `sign` in Julia makes more sense.

On the positive side, since it is a JIT function, doing something like the following internally is still a single function in arrayfire:

```
b = sign(a)
return (1 - b) * (b > 0) - b;
```

**Comment by jpsamaroo** [comment]
Would it make sense to rename `sign` to something like `signbit` instead? I feel like this could trip up some people who, like me, are using `AFArray` as a drop-in replacement for Julia's `Array` to enable GPU offload, and assume that all operations are (approximately) equivalent.

The alternative, of course, is to document and highlight this in the README.

**Comment by ViralBShah** [comment]
ArrayFire should be designed to be as close to the drop-in for Julia Arrays. I think the Julia `signbit` has the same behaviour, but we should change the ArrayFire julia wrapper to return a boolean instead of 1 or 0.

PR appreciated!

**Comment by ranjanan** [comment]
I am unexporting `sign` at the moment, and adding a broadcasted version of `signbit` which works only on v0.5. ( #119 )
