### ISSUE TITLE
Need to write tests

### ISSUE THREAD

**Issue by ranjanan** [JuliaComputing/ArrayFire.jl#11]
A lot of tests are needed.

**Comment by ViralBShah** [comment]
Agreed! Also good to run the examples code you just added in the tests.

**Comment by ranjanan** [comment]
I've added some basic tests now, but yes, it's also a good idea to put some of those examples in there and compare outputs to pure Julia implementations.

**Comment by ViralBShah** [comment]
The tests do not seem to be running as part of CI.

**Comment by ViralBShah** [comment]
Would be nice to enable travis at the very least.

**Comment by ranjanan** [comment]
Wouldn't Travis have to build ArrayFire every single time it runs tests, or is there a way to avoid that?

**Comment by ViralBShah** [comment]
Seems like ubuntu packages are available.

http://packages.ubuntu.com/search?keywords=arrayfire

**Comment by ViralBShah** [comment]
Pkg.test("ArrayFire") fails for me:

````

julia> Pkg.test("ArrayFire")
INFO: Testing ArrayFire
INFO: Setting Unified Backend by default

WARNING: deprecated syntax "call(::Type{AFAbstractArray{T,N}}, ...)".
Use "(::Type{AFAbstractArray{T,N}})(...)" instead.

WARNING: deprecated syntax "call(::Type{AFAbstractArray{T,N}}, ...)".
Use "(::Type{AFAbstractArray{T,N}})(...)" instead.
Assertion failed: (F->isIntrinsic() || findUnmangledSymbol(F->getName()) || SectionMemoryManager::getSymbolAddressInProcess(F->getName())), function addModule, file ./jitlayers.cpp, line 376.
==============================[ ERROR: ArrayFire ]==============================

failed process: Process(`/Users/viral/julia/usr/bin/julia -Cnative -J/Users/viral/julia/usr/lib/julia/sys.dylib --compile=yes --check-bounds=yes --code-coverage=none --color=yes /Users/viral/.julia/v0.5/ArrayFire/test/runtests.jl`, ProcessSignaled(6)) [0]

================================================================================
ERROR: Base.Pkg.PkgError("ArrayFire had test errors")
 [inlined code] from ./strings/io.jl:33
 in #test#55(::Bool, ::Any, ::Array{AbstractString,1}) at ./pkg/entry.jl:671
 [inlined code] from ./int.jl:32
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}})() at ./pkg/dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}}, ::ASCIIString) at ./file.jl:48
 in #cd#1(::Array{Any,1}, ::Any, ::Any, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1}}) at ./pkg/dir.jl:31
 [inlined code] from ./boot.jl:303
 in #test#3(::Bool, ::Any, ::ASCIIString, ::Vararg{ASCIIString}) at ./pkg.jl:228
 in eval(::Module, ::Any) at ./boot.jl:237
````

**Comment by ranjanan** [comment]
This is because of [this commit](https://github.com/JuliaLang/julia/pull/10870). Even `using ArrayFire` fails with that commit.

**Comment by ranjanan** [comment]
This is still a problem on the current julia master. I also suspect some other bugs might have been introduced at some which makes Cxx segfault. I'll verify this and post an issue on Cxx

**Comment by ViralBShah** [comment]
cc @keno. Cxx.jl examples are segfaulting too.

**Comment by ranjanan** [comment]
@ViralBShah There are apparently two distinct bugs, one of which has been fixed, according to @Keno . If you want a version of ArrayFire that works, I'd recommend checking out a Julia commit ID from February.

**Comment by ranjanan** [comment]
There a few tests now, that seem to work. While they're not comprehensive yet, I think from now on we could deal with bugs and add tests based on bug fixes.
