### ISSUE TITLE
repeat is not consistent with Array when outer is 1

### ISSUE THREAD

**Issue by ghost** [JuliaComputing/ArrayFire.jl#113]
For regular Arrays:

julia> x = randn(4,2)
4×2 Array{Float64,2}:
  0.216717   1.91752 
  1.3493    -1.50448 
 -1.89128    0.607526
  0.317094  -1.57292

and

julia> repeat(x, outer=[1,1,1])
4×2×1 Array{Float64,3}:
[:, :, 1] =
  0.216717   1.91752 
  1.3493    -1.50448 
 -1.89128    0.607526
  0.317094  -1.57292 

i.e. we increase the dimension of the array with repeat. With AFArrays:

julia> x = randn(AFArray{Float64}, 4, 2); Array(x)

4×2 Array{Float64,2}:
 -1.35003    0.369328
 -0.121518   0.348746
 -0.28531   -1.59176 
 -0.656605   1.86908 

and

julia> Array(repeat(x, outer=[1,1,1]))
4×2 Array{Float64,2}:
 -1.35003    0.369328
 -0.121518   0.348746
 -0.28531   -1.59176 
 -0.656605   1.86908 

i.e. the dimensions stay the same

**Comment by ranjanan** [comment]
@gaika is this fixed with #121?

**Comment by gaika** [comment]
yep, fixed
