### ISSUE TITLE
PosDefException on cholesky of 2000 x 2000 array in benckmark.jl

### ISSUE THREAD

**Issue by jpsamaroo** [JuliaComputing/ArrayFire.jl#117]
Hey all! I just pulled down ArrayFire.jl this evening, and must say it's a wonderful library! However, I got an error while trying to run the provided benchmark.jl script:

julia> using ArrayFire

julia> include(joinpath(homedir(), ".julia/v0.6/ArrayFire/benchmarks/benchmark.jl"))
INFO: Warmup done!
INFO: Matmul
Time (CPU): 0.251383796
Time (GPU): 0.0329954767
INFO: FFT
Time (CPU): 0.320795333
Time (GPU): 0.0937912699
INFO: Cholesky
ERROR: LoadError: Base.LinAlg.PosDefException(2000)
 in _chol!(::Array{Float32,2}, ::Type{UpperTriangular}) at ./linalg/cholesky.jl:55
 in chol!(::Hermitian{Float32,Array{Float32,2}}) at ./linalg/cholesky.jl:124
 in chol(::Hermitian{Float32,Array{Float32,2}}) at ./linalg/cholesky.jl:145
 in chol(::Array{Float32,2}) at ./linalg/cholesky.jl:186
 in macro expansion at ./util.jl:236 [inlined]
 in benchmark() at /home/jpsamaroo/.julia/v0.6/ArrayFire/benchmarks/benchmark.jl:84
 in include_from_node1(::String) at ./loading.jl:532
 in include(::String) at ./sysimg.jl:14
while loading /home/jpsamaroo/.julia/v0.6/ArrayFire/benchmarks/benchmark.jl, in expression starting on line 107

Here's my versioninfo():
Julia Version 0.6.0-dev.1541
Commit 0dfadd0* (2016-12-10 21:49 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: AMD A10-7860K Radeon R7, 12 Compute Cores 4C+8G
  WORD_SIZE: 64
  BLAS: libopenblas (NO_AFFINITY STEAMROLLER)
  LAPACK: liblapack
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, bdver3)

I've got the above APU installed with drivers, as well as an RX 480, although I'm not exactly sure which GPU is being used here. I'm not mathematically savvy enough to understand what's going, but I assume that for some reason the array being provided to `chol()` is not positive definite (not that I know what that means). I also ran the nmf_benchmark.jl script, which passed with flying colors.

Please let me know if you need any further details!

**Comment by ViralBShah** [comment]
What happens if you try with a smaller matrix?

**Comment by jpsamaroo** [comment]
I've tried random `n x n Float32` matrics with `n = [1995, 1990, 1500, 1000, 100, 10]`, and all of them threw a `PosDefException` every so often (although it occurred much less often with smaller sizes of `n`). I assume this means that `a * a'` is not sufficient to ensure that the matrix is positive-definite? Wikipedia tells me that that's one of the properties necessary for `chol()` to properly factor the matrix. If so, would it make sense to modify the benchmark.jl script to use a matrix which is guaranteed positive-definite, to avoid this issue occurring?
