### ISSUE TITLE
permutedims!

### ISSUE THREAD

**Issue by LaurentPlagne** [JuliaComputing/ArrayFire.jl#123]
Hello,

I have a problem when trying to permute 3D arrays with ArrayFire.jl
`afx` is an `AFArray` of size `(400,200,300)`
`afy` is an `AFArray` of size `(200,300,400)`
`circperm=[2,3,1]`

The _normal_ `permutedims` method is OK 
  `afy=ArrayFire.permutedims(afx,circperm)`
but the _inplace_ produces an error (bounds error)
  `ArrayFire.permutedims!(afy,afx,circperm)`

Note that the corresponding Julia method and arrays works fine...
Note also that circperm is modified by the method (and thus its semantic differs from Julia's method)...

Did I get something wrong (I am a newbie)
Thank you for your help ;)

The message:

 `LoadError: BoundsError: attempt to access (Base.OneTo(200),Base.OneTo(300),Base.OneTo(400))
  at index [4]
 in getindex(::Tuple{Base.OneTo{Int64},Base.OneTo{Int64},Base.OneTo{Int64}}, ::Int64) at ./tuple.jl:8
 in checkdims_perm(::ArrayFire.AFArray{Float32,3}, ::ArrayFire.AFArray{Float32,3}, ::Array{Int64,1}) at ./multidimensional.jl:973
 in permutedims!(::ArrayFire.AFArray{Float32,3}, ::ArrayFire.AFArray{Float32,3}, ::Array{Int64,1}) at ./permuteddimsarray.jl:52
 in macro expansion; at ./util.jl:226 [inlined]
 in macro expansion; at /home/lolo/gitProject/BenchJulia/AFPermute.jl:43 [inlined]
 in anonymous at ./<missing>:?
 in include_string(::String, ::String) at ./loading.jl:441
 in include_string(::Module, ::String, ::String) at /home/lolo/.julia/v0.5/CodeTools/src/eval.jl:32
 in (::Atom.##61#64{String,String})() at /home/lolo/.julia/v0.5/Atom/src/eval.jl:81
 in withpath(::Atom.##61#64{String,String}, ::String) at /home/lolo/.julia/v0.5/CodeTools/src/utils.jl:30
 in withpath(::Function, ::String) at /home/lolo/.julia/v0.5/Atom/src/eval.jl:46
 in macro expansion at /home/lolo/.julia/v0.5/Atom/src/eval.jl:79 [inlined]
 in (::Atom.##60#63{String,String})() at ./task.jl:60
while loading /home/lolo/gitProject/BenchJulia/AFPermute.jl, in expression starting on line 42`

**Comment by ranjanan** [comment]
Hi @LaurentPlagne , only the function `permutedims` is defined for `AFArrays`. Not all of Julia's Base functions are supported by `ArrayFire.jl`. One way of checking whether a function is supported or not is to do the following after entering `using ArrayFire`.

If you do `methods(permutedims)`, you should get a few functions one of which is 

```julia
permutedims{T}(a::ArrayFire.AFArray{T,N<:Any}, perm::Array{Int64,1}) at /Users/ranjan/.julia/v0.5/ArrayFire/src/utils.jl:163
```
which tells you that `ArrayFire` supports `permutedims`. You will

**Comment by LaurentPlagne** [comment]
Thank you for your help ! 
I will try to develop permutedims! by myself because I want to avoid the allocation cost induced by permutedims...  (I use it very often inside an ADI solver)
Thank you again for your wonderful work on Julia.
