### ISSUE TITLE
uncomment `wrap` and `unwrap` ?

### ISSUE THREAD

**Issue by ylxdzsw** [JuliaComputing/ArrayFire.jl#124]
I'm new to here, but I can't find the reason why the [af_unwrap](https://github.com/JuliaComputing/ArrayFire.jl/blob/master/src/wrap.jl#L1650) was commented since the `initial commit`. I'm doing something about convolutional neural network and `unwrap` is useful for me. Is there any possibility that this function get uncommented in the near future?

**Comment by gaika** [comment]
not sure if they work, but at least you can try using them now with v0.1 release.
