### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by okpatil4u** [JuliaComputing/ArrayFire.jl#13]
Can you provide with a broader set of examples ?

**Comment by ranjanan** [comment]
Yes, I have just added an example now. Please check the examples directory.

**Comment by ViralBShah** [comment]
In fact ArrayFire has a nice set of C examples, which would be great for people kicking the tires to implement in Julia.

**Comment by okpatil4u** [comment]
Thanks @ranjanan. @ViralBShah I will have a look at them.
