### ISSUE TITLE
Installation Manjaro Linux

### ISSUE THREAD

**Issue by abieler** [JuliaComputing/ArrayFire.jl#134]
I cannot use the CUDA backend on Manjaro Linux and with OpenCL I get

"ERROR: GLFW wasn't able to initalize"

Here some information I think might be useful from reading through a possibly related issue on Ubuntu:

```
AFInfo()
ArrayFire v3.4.0 (OpenCL, 64-bit Linux, build default)
[0] NVIDIA  : GeForce GTX 1070, 8105 MB


getAvailableBackends()
CPU and OpenCL


Pkg.test("ArrayFire")
INFO: Testing ArrayFire
ERROR: GLFW wasn't able to initalize
INFO: ArrayFire tests passed



setBackend(AF_BACKEND_CUDA)
ERROR: ArrayFire Error (501) : Failed to load dynamic library.



ldd libafcuda.so
	linux-vdso.so.1 (0x00007ffe1eff3000)
	libcudart.so.8.0 => /opt/cuda/lib64/libcudart.so.8.0 (0x00007fe659527000)
	libcublas.so.8.0 => /opt/cuda/lib64/libcublas.so.8.0 (0x00007fe656b77000)
	libcufft.so.8.0 => /opt/cuda/lib64/libcufft.so.8.0 (0x00007fe64dd29000)
	libcusparse.so.8.0 => /opt/cuda/lib64/libcusparse.so.8.0 (0x00007fe64b21b000)
	libnvvm.so.3 => /opt/cuda/nvvm/lib64/libnvvm.so.3 (0x00007fe64a244000)
	libcuda.so.1 => /usr/lib/libcuda.so.1 (0x00007fe64984e000)
	libforge.so.0 => /home/abieler/arrayfire-3/lib/libforge.so.0 (0x00007fe648a56000)
	libGL.so.1 => /usr/lib/libGL.so.1 (0x00007fe6487de000)
	libcusolver.so.8.0 => /opt/cuda/lib64/libcusolver.so.8.0 (0x00007fe64526e000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007fe644ee6000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007fe644be2000)
	libgomp.so.1 => /usr/lib/libgomp.so.1 (0x00007fe6449b4000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fe64479b000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fe64457e000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007fe6441e0000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007fe643fdc000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007fe643dd4000)
	libnvidia-fatbinaryloader.so.375.26 => /usr/lib/libnvidia-fatbinaryloader.so.375.26 (0x00007fe643b88000)
	libfontconfig.so.1 => /usr/lib/libfontconfig.so.1 (0x00007fe643942000)
	libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007fe643681000)
	libglfw.so.3 => /usr/lib/libglfw.so.3 (0x00007fe64346a000)
	libX11.so.6 => /usr/lib/libX11.so.6 (0x00007fe64312b000)
	libXext.so.6 => /usr/lib/libXext.so.6 (0x00007fe642f19000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x000055608b692000)
	libGLX.so.0 => /usr/lib/libGLX.so.0 (0x00007fe642ce8000)
	libGLdispatch.so.0 => /usr/lib/libGLdispatch.so.0 (0x00007fe642a10000)
	libexpat.so.1 => /usr/lib/libexpat.so.1 (0x00007fe6427e6000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007fe6425d0000)
	libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007fe6423c0000)
	libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007fe64218a000)
	libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0x00007fe641f25000)
	libwayland-client.so.0 => /usr/lib/libwayland-client.so.0 (0x00007fe641d16000)
	libwayland-cursor.so.0 => /usr/lib/libwayland-cursor.so.0 (0x00007fe641b0e000)
	libwayland-egl.so.1 => /usr/lib/libwayland-egl.so.1 (0x00007fe64190c000)
	libxkbcommon.so.0 => /usr/lib/libxkbcommon.so.0 (0x00007fe6416cc000)
	libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007fe6414a3000)
	libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007fe64118e000)
	libgraphite2.so.3 => /usr/lib/libgraphite2.so.3 (0x00007fe640f62000)
	libffi.so.6 => /usr/lib/libffi.so.6 (0x00007fe640d59000)
	libXau.so.6 => /usr/lib/libXau.so.6 (0x00007fe640b55000)
	libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007fe64094f000)
	libpcre.so.1 => /usr/lib/libpcre.so.1 (0x00007fe6406dc000)



```

**Comment by pavanky** [comment]
How did you install arrayfire ?

**Comment by abieler** [comment]
From AUR through the system installer (octopi). I tried also with downloading the binary but that did not work either.

**Comment by pavanky** [comment]
@abieler The output of `af::info()` seems to be off. Can you run `sudo updatedb && locate libafcuda.so` and show the output?

**Comment by abieler** [comment]
I managed to fix the OpenCL issue. Somehow glfw-wayland had been installed. Replaced it with glfw-x11. This fixes the "ERROR: GLFW wasn't able to initalize" issue.

The CUDA problem is still there.

Here the output of the locate:

/home/abieler/arrayfire-3/lib/libafcuda.so
/home/abieler/arrayfire-3/lib/libafcuda.so.3
/home/abieler/arrayfire-3/lib/libafcuda.so.3.4.2
/usr/lib/libafcuda.so
/usr/lib/libafcuda.so.3
/usr/lib/libafcuda.so.3.4.0

**Comment by pavanky** [comment]
@abieler looks like there are multiple versions installed on your machine. Which one did you run the ldd on ?

**Comment by abieler** [comment]
Yes the one in the home directory is the binary download one, the other from the AUR.
Here ldd for both as I am not sure that I did it on the AUR one as I intended:

ldd arrayfire-3/lib/libafcuda.so
        linux-vdso.so.1 (0x00007fff4ad59000)
        libcudart.so.8.0 => /opt/cuda/lib64/libcudart.so.8.0 (0x00007f5687ead000)
        libcublas.so.8.0 => /opt/cuda/lib64/libcublas.so.8.0 (0x00007f56854fd000)
        libcufft.so.8.0 => /opt/cuda/lib64/libcufft.so.8.0 (0x00007f567c6af000)
        libcusparse.so.8.0 => /opt/cuda/lib64/libcusparse.so.8.0 (0x00007f5679ba1000)
        libnvvm.so.3 => /opt/cuda/nvvm/lib64/libnvvm.so.3 (0x00007f5678bca000)
        libcuda.so.1 => /usr/lib/libcuda.so.1 (0x00007f56781d4000)
        libforge.so.0 => /home/abieler/arrayfire-3/lib/libforge.so.0 (0x00007f56773dc000)
        libGL.so.1 => /usr/lib/libGL.so.1 (0x00007f5677164000)
        libcusolver.so.8.0 => /opt/cuda/lib64/libcusolver.so.8.0 (0x00007f5673bf4000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f567386c000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f5673568000)
        libgomp.so.1 => /usr/lib/libgomp.so.1 (0x00007f567333a000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f5673121000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f5672f04000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f5672b66000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f5672962000)
        librt.so.1 => /usr/lib/librt.so.1 (0x00007f567275a000)
        libnvidia-fatbinaryloader.so.375.26 => /usr/lib/libnvidia-fatbinaryloader.so.375.26 (0x00007f567250e000)
        libfontconfig.so.1 => /usr/lib/libfontconfig.so.1 (0x00007f56722c8000)
        libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007f5672007000)
        libglfw.so.3 => /usr/lib/libglfw.so.3 (0x00007f5671de9000)
        libX11.so.6 => /usr/lib/libX11.so.6 (0x00007f5671aaa000)
        libXext.so.6 => /usr/lib/libXext.so.6 (0x00007f5671898000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x000055a54a82b000)
        libGLX.so.0 => /usr/lib/libGLX.so.0 (0x00007f5671667000)
        libGLdispatch.so.0 => /usr/lib/libGLdispatch.so.0 (0x00007f567138f000)
        libexpat.so.1 => /usr/lib/libexpat.so.1 (0x00007f5671165000)
        libz.so.1 => /usr/lib/libz.so.1 (0x00007f5670f4e000)
        libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007f5670d3e000)
        libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007f5670b08000)
        libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0x00007f5670876000)
        libXrandr.so.2 => /usr/lib/libXrandr.so.2 (0x00007f567066b000)
        libXinerama.so.1 => /usr/lib/libXinerama.so.1 (0x00007f5670468000)
        libXxf86vm.so.1 => /usr/lib/libXxf86vm.so.1 (0x00007f5670262000)
        libXcursor.so.1 => /usr/lib/libXcursor.so.1 (0x00007f5670057000)
        libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007f566fe2e000)
        libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007f566fb19000)
        libgraphite2.so.3 => /usr/lib/libgraphite2.so.3 (0x00007f566f8ed000)
        libXrender.so.1 => /usr/lib/libXrender.so.1 (0x00007f566f6e2000)
        libXfixes.so.3 => /usr/lib/libXfixes.so.3 (0x00007f566f4dc000)
        libXau.so.6 => /usr/lib/libXau.so.6 (0x00007f566f2d8000)
        libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007f566f0d2000)
        libpcre.so.1 => /usr/lib/libpcre.so.1 (0x00007f566ee5d000)



ldd /usr/lib/libafcuda.so
        linux-vdso.so.1 (0x00007fff14bab000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f47c02ca000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f47c00c6000)
        librt.so.1 => /usr/lib/librt.so.1 (0x00007f47bfebe000)
        libcublas.so.7.5 => not found
        libfreeimage.so.3 => /usr/lib/libfreeimage.so.3 (0x00007f47bf61d000)
        libcufft.so.7.5 => not found
        libcusparse.so.7.5 => not found
        libnvvm.so.3 => /opt/cuda/nvvm/lib64/libnvvm.so.3 (0x00007f47be644000)
        libcuda.so.1 => /usr/lib/libcuda.so.1 (0x00007f47bdc4e000)
        libforge.so.0 => /home/abieler/arrayfire-3/lib/libforge.so.0 (0x00007f47bce58000)
        libGL.so.1 => /usr/lib/libGL.so.1 (0x00007f47bcbe0000)
        libcusolver.so.7.5 => not found
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f47bc856000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f47bc552000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f47bc33b000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f47bbf9d000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00005577fe1df000)
        libnvidia-fatbinaryloader.so.375.26 => /usr/lib/libnvidia-fatbinaryloader.so.375.26 (0x00007f47bbd51000)
        libfontconfig.so.1 => /usr/lib/libfontconfig.so.1 (0x00007f47bbb0d000)
        libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007f47bb84a000)
        libglfw.so.3 => /usr/lib/libglfw.so.3 (0x00007f47bb62c000)
        libX11.so.6 => /usr/lib/libX11.so.6 (0x00007f47bb2ed000)
        libXext.so.6 => /usr/lib/libXext.so.6 (0x00007f47bb0db000)
        libGLX.so.0 => /usr/lib/libGLX.so.0 (0x00007f47baeaa000)
        libGLdispatch.so.0 => /usr/lib/libGLdispatch.so.0 (0x00007f47babd4000)
        libexpat.so.1 => /usr/lib/libexpat.so.1 (0x00007f47ba9a8000)
        libz.so.1 => /usr/lib/libz.so.1 (0x00007f47ba791000)
        libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007f47ba581000)
        libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007f47ba34b000)
        libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0x00007f47ba0bb000)
        libXrandr.so.2 => /usr/lib/libXrandr.so.2 (0x00007f47b9eb0000)
        libXinerama.so.1 => /usr/lib/libXinerama.so.1 (0x00007f47b9cab000)
        libXxf86vm.so.1 => /usr/lib/libXxf86vm.so.1 (0x00007f47b9aa5000)
        libXcursor.so.1 => /usr/lib/libXcursor.so.1 (0x00007f47b989a000)
        libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007f47b9671000)
        libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007f47b935e000)
        libgraphite2.so.3 => /usr/lib/libgraphite2.so.3 (0x00007f47b9132000)
        libXrender.so.1 => /usr/lib/libXrender.so.1 (0x00007f47b8f25000)
        libXfixes.so.3 => /usr/lib/libXfixes.so.3 (0x00007f47b8d1f000)
        libXau.so.6 => /usr/lib/libXau.so.6 (0x00007f47b8b1b000)
        libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007f47b8915000)
        libpcre.so.1 => /usr/lib/libpcre.so.1 (0x00007f47b86a2000)

**Comment by pavanky** [comment]
Please delete the one in /usr/lib. Julia wrapper seems to be picking up 3.4.0 which does not Compute 6.0 cards.

**Comment by abieler** [comment]
Removed both versions and did a new ArrayFire install of the downloadable binary under /usr/local.
I now have all 3 backends available.

However Pkg.test("ArrayFire") throws an error:

```
ERROR: LoadError: ArrayFire Error (998) : Internal error
 in throwAFerror(::Int32) at /home/abieler/.julia/v0.5/ArrayFire/src/error.jl:50
 in convert(::Type{ArrayFire.AFArray{Float32,2}}, ::Array{Float32,2}) at /home/abieler/.julia/v0.5/ArrayFire/src/create.jl:27
 in ArrayFire.AFArray{T,N}(::Array{Float32,2}) at /home/abieler/.julia/v0.5/ArrayFire/src/create.jl:31
while loading /home/abieler/.julia/v0.5/ArrayFire/test/runtests.jl, in expression starting on line 6
========================================================[ ERROR: ArrayFire ]=========================================================

failed process: Process(`/usr/bin/julia -Cx86-64 -J/usr/lib/julia/sys.so --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes /home/abieler/.julia/v0.5/ArrayFire/test/runtests.jl`, ProcessExited(1)) [1]

=====================================================================================================================================
```

**Comment by pavanky** [comment]
Can you run Julia with `AF_PRINT_ERRORS=1` exported ?

**Comment by abieler** [comment]
In function std::string cuda::getCUDARuntimeVersion()
In file src/backend/cuda/platform.cpp:259
CUDA Error (30): unknown error


In function af_err af_create_array(void**, const void*, unsigned int, const dim_t*, af_dtype)
In file src/api/c/array.cpp:67

**Comment by pavanky** [comment]
Did you upgrade the driver or the kernel recently ? That looks like a driver error.

**Comment by abieler** [comment]
Yes the kernel was updated. Looking into driver settings now

**Comment by pavanky** [comment]
You'll need to reboot to use CUDA.

**Comment by abieler** [comment]
reinstalled the nvidia driver & reboot solved it. Thanks for the very prompt help!

**Comment by ranjanan** [comment]
@abieler if this issue is resolved, could you close it? Thanks @pavanky for helping out.
