### ISSUE TITLE
benchmarking FFT GPU against CPU

### ISSUE THREAD

**Issue by bradleyashton** [JuliaComputing/ArrayFire.jl#135]
I am trying to establish the level of speedup I can gain using 2D FFT on GPU for a common use case. I want to check that I am writing sensible benchmarks, and getting the full hardware benefit. I get a factor of 17 improvement over CPU Matlab, i.e. 7x faster than Matlab's GPU toolbox. 

I am not sure if this is what I should expect, given the benchmarks I have seen at [ArrayFire.jl.](https://github.com/JuliaComputing/ArrayFire.jl) which suggest there might be a factor of 30 to gain over CPU. The comparison also involves some steps to get the full effect of FFTW in julia on the CPU, also needed for julia to be comparable to Matlab.

My benchmarks are against MATLAB 2015b running on:
```shell
abradley@kolmogorov:~$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    2
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 60
Stepping:              3
CPU MHz:               800.000
BogoMIPS:              6796.20
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              8192K
NUMA node0 CPU(s):     0-7
```
with 
```shell
abradley@kolmogorov:~$ grep -i 'Model' /proc/cpuinfo
model		: 60
model name	: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
model		: 60
model name	: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
model		: 60
model name	: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
model		: 60
model name	: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
model		: 60
model name	: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
model		: 60
model name	: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
model		: 60
model name	: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
model		: 60
model name	: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
```

The GPU hardware is
```julia
julia> AFInfo()
ArrayFire v3.5.0 (CUDA, 64-bit Linux, build e59cdbc)
Platform: CUDA Toolkit 7, Driver: 367.57
[0] Tesla K40c, 11440 MB, CUDA Compute 3.5
-1- Tesla K40c, 11440 MB, CUDA Compute 3.5
```
and for julia the versioninfo is 
```julia
julia> versioninfo()
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACK NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, has well)
```

In julia, I do the following:
```julia
julia> using ArrayFire

julia> FFTW.set_num_threads(Sys.CPU_CORES)
```
important to get the full benefit of planning. Matlab seems to cache FFT plans, so to give a fair comparison, in julia we do the FFT plan after setting the number of threads (here Sys.CPU_CORES=8). 

Next, a minimal plan (to compare with Matlab's rapid execution; longer planning can give a little further gain).

```julia
function make_ffts(a)
         P = plan_fft!(a;flags=FFTW.MEASURE)
         Q = inv(P);
         return P, Q
       end
make_ffts (generic function with 1 method)
```

Now the FFT call on the GPU, using in place fft
```julia
julia> function fast_fourier(a::ArrayFire.AFArray{Complex{Float64},2},n::Int)
                  for i = 1:n
                      fft!(a);
                  end
                  sync(0);
       end
fast_fourier (generic function with 1 method)
```

Now a warmup to initialise the plan, and compile

```julia
julia> function warmup(n::Int)
                  a = complex(randn(Float64, n,n),randn(Float64,n,n))::Array{Complex{Float64},2};
                  P, Q = make_ffts(a)
           
                  ad = AFArray(a);
                  P*a;
                  fft!(ad);
                  fast_fourier(ad,1);
               return P, Q
              end
warmup (generic function with 1 method)
```

Finally, the benchmark:
```julia
julia> function benchmark(m::Int,n::Int)
                  
                  P, Q=warmup(m);
                  info("Warmup done!")

                  a = complex(randn(Float64, m,m),randn(Float64,m,m))::Array{Complex{Float64},2};
                  ad = AFArray(a);

                  #FFT
                  info("FFT")
                  t1 = @elapsed P*a; 
                  t2 = @elapsed fast_fourier(ad,n)
                  println("Time (CPU): $(t1)") 
                  println("Time (GPU): $(t2/n)")
              println("speedup: $(t1*n/t2)")
              #ArrayFire.af_device_gc()
              end
benchmark (generic function with 1 method)
```

In matlab I get (after a warmup):

```julia
>> n=2048;a=randn(n,n)+i*randn(n,n);tic; for ind=1:100; a=fft2(a);end; tMatlab=toc/100

tMatlab =

    0.0420
```

The result in julia is
```julia
julia> benchmark(2048,100)
INFO: Warmup done!
INFO: FFT
Time (CPU): 0.020555077
Time (GPU): 0.00241797102
speedup: 8.500960859324111

julia> tGPUoverMATLAB=.0420/.00242
17.355371900826448
```

So in this case ArrayFire.jl is 17 times faster than an 8 core CPU running Matlab. Interestingly, it is only 8.5 times faster than julia's planned FFT on the CPU. Switching to `Float32` doesn't change this much (and isn't desirable for what I want to do).

Questions:

1. First and foremost, am I maxing out this benchmark?

2. I compiled `arrayfire` using 8 threads, and I have no idea if this is optimal. Is there any documentation on how to set the number of threads when compiling?

3. Am I getting the benefit of both cards? Is there any way to do this for a single job or does it only make sense to run independent jobs on each card (presumably there would have to be some high-speed communication for it to be worthwhile)

4. I understand that currently `cuFFTW` doesn't support planning (only API) as it is all done internally and cached beforehand. Given the big gains from FFTW planning for static arrays on CPU, is there any scope for, or need for, additional planning using array information? I'm guessing @stevengj might have some insight here

Sorry for the mega-post, any thoughts greatly appreciated!

**Comment by pavanky** [comment]
@bradleyashton I haven't looked through the entire post, but are you calling `sync` before starting and stopping the timers? If not you are just measuring the time it takes to queue the operation on the GPU not finish it.

**Comment by pavanky** [comment]
Nevermind, I see that you are calling sync. Let me read the post now :)

**Comment by bradleyashton** [comment]
also thanks to @pavanky who has already given some feedback on point 4. over at #133 . It would be interesting to know what the philosophy is here: are GPU's too hard to plan on for FFTW?

**Comment by pavanky** [comment]
@bradleyashton 

1) 2048 x 2048 may be close to peak, but I'd try a few larger sizes to see if the difference in performance increases. If you are operating at this size, try adding more batches to see if that scales the performance better (i.e. use 2048 x 2048 x 10 instead of 2048 x 2048).

2) Shouldn't matter for the CUDA backend.

3) No you are using only 1 GPU at a time. You can however switch between two GPUs using whatever the equivalent of setDevice is and distribute work between the two GPUs manually. But currently there is no way to transfer data between two gpus automatically. You'll need to do a transfer using `GPU0 -> CPU -> GPU1`

4) Unfortunately CUFFT and CUFFTW are closed source and are quite opaque on their optimization techniques. That said, one thing that can be improved from arrayfire end is support FFT on mutliple GPUs natively. 
 
------------------------
As for coming back to your expected improvement of 30x from the README, those benchmarks were done on an Amazon EC2 instance as far as I can tell. There are also the following reasons why you are seeing a smaller speedup:

1) That benchmark was for single precision compared to double precision benchmark being used here.

2)  Each core on your desktop runs at a higher clock frequency than the Xeon. If the problem size was larger, there would have been problem sizes where the Xeons would perform better because of larger cache sizes, but for 2048 x 2048, the entire problem fits inside the GPU.

**Comment by bradleyashton** [comment]
Thanks, that's extremely helpful
