### ISSUE TITLE
Running an example from array fire is giving the following error : warning: libglfw.so.3, needed by /lib/libforge.so.0, not found

### ISSUE THREAD

**Issue by pranaviyalamanchili** [JuliaComputing/ArrayFire.jl#140]
I ran the command ldd libafcpu.so.3

The output looks like the following:
linux-vdso.so.1 =>  (0x00007ffdd553b000)
	libgomp.so.1 => /lib64/libgomp.so.1 (0x00007fd525d34000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fd525b30000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fd525913000)
	libforge.so.0 => not found
	libGL.so.1 => /usr/lib64/nvidia/libGL.so.1 (0x00007fd5255e3000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fd5252e0000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fd524fd8000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fd524dc2000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fd524a00000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd530463000)
	libnvidia-tls.so.352.39 => /usr/lib64/nvidia/tls/libnvidia-tls.so.352.39 (0x00007fd5247fd000)
	libnvidia-glcore.so.352.39 => /usr/lib64/nvidia/libnvidia-glcore.so.352.39 (0x00007fd521d6b000)
	libX11.so.6 => /lib64/libX11.so.6 (0x00007fd521a2c000)
	libXext.so.6 => /lib64/libXext.so.6 (0x00007fd52181a000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x00007fd5215f8000)
	libXau.so.6 => /lib64/libXau.so.6 (0x00007fd5213f3000)

and also ldd libforge.so.0
ldd: warning: you do not have execution permission for `./libforge.so.0'
	linux-vdso.so.1 =>  (0x00007ffe5b18e000)
	libfontconfig.so.1 => /lib64/libfontconfig.so.1 (0x00007f4d1ad50000)
	libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007f4d1aaaa000)
	libglfw.so.3 => not found
	libGL.so.1 => /usr/lib64/nvidia/libGL.so.1 (0x00007f4d1a779000)
	libX11.so.6 => /lib64/libX11.so.6 (0x00007f4d1a43b000)
	libXext.so.6 => /lib64/libXext.so.6 (0x00007f4d1a228000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f4d19f20000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f4d19c1e000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f4d19a07000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f4d197eb000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f4d1942a000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4d1bd8b000)
	libexpat.so.1 => /lib64/libexpat.so.1 (0x00007f4d191ff000)
	libnvidia-tls.so.352.39 => /usr/lib64/nvidia/tls/libnvidia-tls.so.352.39 (0x00007f4d18ffc000)
	libnvidia-glcore.so.352.39 => /usr/lib64/nvidia/libnvidia-glcore.so.352.39 (0x00007f4d1656a000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f4d16365000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x00007f4d16143000)
	libXau.so.6 => /lib64/libXau.so.6 (0x00007f4d15f3e000)

**Comment by pavanky** [comment]
@pranaviyalamanchili You will need to install glfw on your system.

On a side note, your name totally startled me a for a minute :)

**Comment by pranaviyalamanchili** [comment]
Oh yeah we share the same second name !! Hope you did'nt have people asking you "what is it again? Lemon chilli? :p

I am trying to implement the examples on a cluster at my school. Apparently I am not allowed to install without permissions. I managed to include the libraries and inlcudes from AF and created a makefile. Installing glfw is the only solution?

**Comment by pavanky** [comment]
@pranaviyalamanchili You can build arrayfire from source by disabling graphics. This may take a while.

Alternatively if you know could just download this file :) http://ci.arrayfire.org/userContent/Linux/ArrayFire-no-gl-v3.4.2_Linux_x86_64.sh

For future downloads, go to the arrayfire download page, and click on the link that says something like "older installers". From there you can find the right version folder, which will contain various installers including some containing `no-gl` in their name. Just use this installation file instead.

**Comment by pranaviyalamanchili** [comment]
Thank you for this link. 
I could compile the code.
Now I have a different error when i run the code

 error while loading shared libraries: libafcpu.so.3: cannot open shared object file: No such file or directory

**Comment by pranaviyalamanchili** [comment]
Oh no. I added to the library path. Its working yay :)

Thanks much pavan for the help

**Comment by ranjanan** [comment]
Thanks @pavanky for helping out with this.
