### ISSUE TITLE
ArrayFire library not found

### ISSUE THREAD

**Issue by 4lrdyD** [JuliaComputing/ArrayFire.jl#141]
I installed ArrayFire in Julia with Pkg.add("ArrayFire") and aparently install it without any problem, but when i use Pkg.test("ArrayFire") the promt return  "ArrayFire library not found". I don't know what happen. Any idea?

julia> Pkg.test("ArrayFire")
INFO: Testing ArrayFire
ERROR: LoadError: LoadError: LoadError: ArrayFire library not found
 in error(::String) at .\error.jl:21
 in include_from_node1(::String) at .\loading.jl:488 (repeats 2 times)
 in eval(::Module, ::Any) at .\boot.jl:234
 in require(::Symbol) at .\loading.jl:415
 in include_from_node1(::String) at .\loading.jl:488
 in process_options(::Base.JLOptions) at .\client.jl:262
 in _start() at .\client.jl:318
while loading C:\Users\user\.julia\v0.5\ArrayFire\src\config.jl, in expression starting on line 8
while loading C:\Users\user\.julia\v0.5\ArrayFire\src\ArrayFire.jl, in expression starting on line 7
while loading C:\Users\user\.julia\v0.5\ArrayFire\test\runtests.jl, in expression starting on line 1
==============================[ ERROR: ArrayFire ]==============================

failed process: Process(`'C:\Users\user\AppData\Local\Julia-0.5.0\bin\julia' -Cx86-64 '-JC:\Users\user\AppData\Local\Julia-0.5.0\lib\julia\sys.dll' --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes 'C:\Users\user\.julia\v0.5\ArrayFire\test\runtests.jl'`, ProcessExited(1)) [1]

================================================================================
ERROR: ArrayFire had test errors
 in #test#61(::Bool, ::Function, ::Array{AbstractString,1}) at .\pkg\entry.jl:740
 in (::Base.Pkg.Entry.#kw##test)(::Array{Any,1}, ::Base.Pkg.Entry.#test, ::Array{AbstractString,1}) at .\<missing>:0
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}})() at .\pkg\dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}}, ::String) at .\file.jl:48
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at .\pkg\dir.jl:31
 in (::Base.Pkg.Dir.#kw##cd)(::Array{Any,1}, ::Base.Pkg.Dir.#cd, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at .\<missing>:0
 in #test#3(::Bool, ::Function, ::String, ::Vararg{String,N}) at .\pkg\pkg.jl:258
 in test(::String, ::Vararg{String,N}) at .\pkg\pkg.jl:258

**Comment by pavanky** [comment]
Did you install the arrayfire libraries?

**Comment by 4lrdyD** [comment]
I only use Pkg.add("ArrayFire"), and i tried use Pkg.test("ArrayFire") As I read in 
https://github.com/JuliaComputing/ArrayFire.jl 
but return the error. 
I have to do something else?

**Comment by pavanky** [comment]
Did you follow the installation instructions in the README: https://github.com/JuliaComputing/ArrayFire.jl/blob/master/README.md

This repo is only has the Julia bindings for arrayfire. You still need to get the arrayfire dlls using the method described above.

**Comment by 4lrdyD** [comment]
thanks for help and sorry for the insistence, but the README.md is the same I saw, for Windows says that Arrayfire requires vcomp120.dll, i have installed Microsoft Visual C++ 2013 Redistributable. You mean this dll?, how i see if i have this dll?

**Comment by pavanky** [comment]
Did you download the arrayfire installers and install them ?

**Comment by 4lrdyD** [comment]
I only use Pkg.add in the prompt of Julia

**Comment by pavanky** [comment]
@4lrdyD you'll need to download and install the C / C++ library from here; https://arrayfire.com/download-splash/?redirect_to=/download

**Comment by 4lrdyD** [comment]
sorry i realized my mistake, it's the step i ignored, I thought that just using Pkg.add was enough, but i was wrong. thanks a lot and sorry for the inconveniences, greetings
