### ISSUE TITLE
Abs of a complex array is not working

### ISSUE THREAD

**Issue by arsenal9971** [JuliaComputing/ArrayFire.jl#143]
When I run the next code to get the magnitude of each entry of the complex matrix, the result is complex with some precision issues and the actual magnitude repeated in the real and in the imaginary part of the array

```julia
using ArrayFire
A = AFArray(ones(Float32,3,3)+im*ones(Float32,3,3))
abs(A)
```
(One more question if I can, is there any fast way to compute the transpose of an AFArray on the device, and not stream it first to the host?)

**Comment by pavanky** [comment]
@arsenal9971 Transpose should not get the array to host. What are you doing right now ?

**Comment by arsenal9971** [comment]
A have an array A that is an ArrayFire.AFArray{Complex{Float32},3} of size 256x256x49 and I want to do the next operation 

```julia
RMS = transpose(sum(squeeze(sum(real(abs(shearlets)).^2,1),1),1))
```
this operation takes **3.399006 seconds (527.07 k allocations: 11.489 MB)**, if I send to the host first the AFArray and apply the same operation, i.e. 
```julia
RMS = transpose(sum(squeeze(sum(abs(Array(shearlets)).^2,1),1),1))
```
which takes **0.084337 seconds (61 allocations: 49.050 MB, 10.69% gc time)**
when I decompose the operation step by step I realize that after doing `squeeze(sum(real(abs(shearlets)).^2,1),1)` I notice this last array is of type ** Base.ReshapedArray{Float32,2,ArrayFire.AFArray{Float32,3},Tuple{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64}}}**, and doing operations on this type is super costly and sends the array to the host. Is there any form to squeeze an array without that cost?

**Comment by pavanky** [comment]
@arsenal9971 can you show the output of ArrayFire.info() ?
@ranjanan This doesn't sound right. Any idea where the transfer to the cpu is happening ?

**Comment by ranjanan** [comment]
@arsenal9971 With regard to your first question, `transpose` does not take the array to the host.
 
```julia
julia> c = rand(AFArray{Float32}, 2, 2)
2×2 ArrayFire.AFArray{Float32,2}:
 0.399046  0.533852
 0.671998  0.138579

julia> transpose(c)
2×2 ArrayFire.AFArray{Float32,2}:
 0.399046  0.671998
 0.533852  0.138579

julia> transpose!(c)
2×2 ArrayFire.AFArray{Float32,2}:
 0.399046  0.671998
 0.533852  0.138579
```

**Comment by ranjanan** [comment]
As for your second comment, I don't think ArrayFire.jl supports `squeeze` (@pavanky, is there a function for this in the c++ library?). What's happening is that in Julia, `squeeze` is falling back to the AbstractArray implementation, which creates a `ReshapedArray` type, which when summed, seems to create a CPU copy to which new values are written in a loop. This is why I think this is slower.

**Comment by pavanky** [comment]
I don't know what squeeze does..

**Comment by ranjanan** [comment]
Also, the original issue is addressed by #145

**Comment by ranjanan** [comment]
@pavanky It removes a particular dimension. For example, 

```julia
julia> a = reshape(collect(1:4),(2,2,1,1))
2×2×1×1 Array{Int64,4}:
[:, :, 1, 1] =
 1  3
 2  4

julia> squeeze(a, 4)
2×2×1 Array{Int64,3}:
[:, :, 1] =
 1  3
 2  4
```
Check [this](http://docs.julialang.org/en/stable/stdlib/arrays/?highlight=squeeze#Base.squeeze) out for more info.

**Comment by pavanky** [comment]
@ranjanan are you holding the dimension data in the wrapper or are you using arrayfire ? This is because in arrayfire both those arrays are equivalent.

**Comment by ranjanan** [comment]
>This is because in arrayfire both those arrays are equivalent.

Yes, you are right, with regard to the trailing dimensions. But (an equivalent to) the following is what @arsenal9971 is trying to do:

```julia
julia> a
1×256×49 ArrayFire.AFArray{Float32,3}:
...
julia> b # same content and structure as a
1×256×49 Array{Float32,3}: 
...
julia> a[1, :, :] # ArrayFire indexing behaviour (and Julia v0.4)
1×256×49 ArrayFire.AFArray{Float32,3}:
....
julia> b[1,:,:] # Julia indexing behaviour (on v0.5 and greater)
256×49 Array{Float32,2}:
```

Now to achieve the latter behaviour a `squeeze(x, 1)` would be nice to remove the first dimension. I was wondering if there were an ArrayFire c++ function like that.

**Comment by ranjanan** [comment]
Hmmm, @arsenal9971 instead of squeeze(x, 1), maybe you can use `reshape`? In the above example, you can do `reshape(x, 256, 49)`, and then the rest.

**Comment by arsenal9971** [comment]
@pavanky I got an empty output when typing in the julia REPL ArrayFire.info() (after calling ArrayFire library)

@ranjanan thanks, actually reshape works perfectly and takes way less time and memory, with the next code
```julia
reshape(sum(real(abs(shearlets)).^2,1),size(shearlets,2),size(shearlets,3))
```
with **0.000706 seconds (52 allocations: 1.297 KB)**,thanks

**Comment by ranjanan** [comment]
@arsenal9971 You're probably looking for `ArrayFire.AFInfo()` (I think `AFInfo()` should just work too). It displays ArrayFire version details and the device you're on. If you think all your questions are answered in this issue, would you mind closing the issue please?

**Comment by arsenal9971** [comment]
Ok, here is the output
```
ArrayFire v3.3.2 (OpenCL, 64-bit Mac OSX, build f65dd97)
[0] APPLE   : Intel(R) Iris(TM) Graphics 6100, 1536 MB
```

**Comment by pavanky** [comment]
@arsenal9971 Intel GPU is not going to give you a significant performance boost over the CPUs.

@ranjanan I think squeeze needs to be implemented in the wrapper using moddims / reshape.

**Comment by arsenal9971** [comment]
@pavanky Surprisingly as I am developing a library that uses extensively fft and ifft the performance is improved very well (here some https://github.com/arsenal9971/Shearlab.jl/blob/master/benchmarks/README.md), and it will be used in some Nvidia cards soon.


 I have an extra question maybe for @ranjanan when I want to build in travis a julia package that uses ArrayFire on linux and OSX, what should I put in the .travis.yaml file?, I tried for linux with the lines that you used in .travis.yaml of ArrayFire.jl
```
install:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - sudo apt-get update
  - sudo apt-get install libfreeimage-dev libatlas3gf-base libfftw3-dev cmake
  - wget http://ci.arrayfire.org/userContent/Linux/ArrayFire-no-gl-v3.4.2_Linux_x86_64.sh
  - ls -l
  - sudo chmod +x ArrayFire-no-gl-v3.4.2_Linux_x86_64.sh
  - sudo ./ArrayFire-no-gl-v3.4.2_Linux_x86_64.sh --exclude-subdir --prefix=/usr/local
before_script:
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/
```
and is having build errors, what can be the solution for the osx one?

**Comment by gaika** [comment]
```
using ArrayFire
A = AFArray(ones(Float32,3,3)+im*ones(Float32,3,3))
abs(A)
AFArray: 3×3 Array{Float32,2}:
 1.41421  1.41421  1.41421
 1.41421  1.41421  1.41421
 1.41421  1.41421  1.41421
```
