### ISSUE TITLE
fft does not return AFarray

### ISSUE THREAD

**Issue by rveltz** [JuliaComputing/ArrayFire.jl#157]
Hi,

I am using the package under v0.6:
```julia
julia> versioninfo()
Julia Version 0.6.0
Commit 903644385b (2017-06-19 13:05 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
```
with the following commit. I don't remember if I am using [#121](https://github.com/JuliaComputing/ArrayFire.jl/pull/121)...

```julia
Pkg.status("ArrayFire")
WARNING: unknown ArrayFire commit c286d4ee, metadata may be ahead of package cache
 - ArrayFire                     0.0.3+             master
```

Anyway, doing this simple operation

```julia
a1 = rand(AFArray{Float32},128);
b1 = fft(a1);
typeof(b1) #Array{Complex{Float32},1}!!
```

returns a `Array{Complex{Float32},1}`. Any thought where this might come from?

Thank you.

**Comment by gaika** [comment]
sorry, should be a bug in #121 branch - fft default arguments are not implemented yet, so the call happens to go to julia standard library. If you can help with tests for fft then I can hook up default arguments that would match julia standard library behavior (as discussed in https://github.com/gaika/ArrayFire.jl/issues/3 ).

For now you can use fft(_in::AFArray{T,N},norm_factor::Real,odim0::dim_t) and similar ones found in wrap.jl

**Comment by rveltz** [comment]
Indeed, `b2=ArrayFire.fft(a1,1.,128);` seems to work. However it returns a vector with no imaginary part.

**Comment by gaika** [comment]
@rveltz  oops, let me fix that.

**Comment by gaika** [comment]
fixed in https://github.com/gaika/ArrayFire.jl/commit/bb4a613416088bdb4dc1fc7aef5f420db93aadd1

**Comment by rveltz** [comment]
Excellent! Thank you.
