### ISSUE TITLE
ERROR: InitError: ArrayFire Error (501) : Failed to load dynamic library. See http://www.arrayfire.com/docs/unifiedbackend.htm for instructions to set up environment for Unified backend

### ISSUE THREAD

**Issue by mohamed82008** [JuliaComputing/ArrayFire.jl#161]
I get the following error when I run `using ArrayFire` in Linux: 
```
ERROR: InitError: ArrayFire Error (501) : Failed to load dynamic library. See http://www.arrayfire.com/docs/unifiedbackend.htm for instructions to set up environment for Unified backend
```
I already added the directory having libaf.so to my LD_PATH_LIBRARY in the bashrc, so I wonder what else could be causing this problem?

**Comment by gaika** [comment]
Make sure all required libraries are in place (glfw, nvrtc, etc.), then make sure you can run ArrayFire examples. Sometimes you have to run `ldconfig` as root after install to update all the linking:

```
# ldd /usr/lib/libaf.so | grep "not found"
# ldd /usr/lib/libafcuda.so | grep "not found"
# ldconfig
```

**Comment by mohamed82008** [comment]
Seems like the following are not found, although I have Cuda:
```
	libcudart.so.8.0 => not found
	libcublas.so.8.0 => not found
	libcufft.so.8.0 => not found
	libcusparse.so.8.0 => not found
	libcusolver.so.8.0 => not found
	libnvrtc.so.8.0 => not found
	libforge.so.1 => not found
```

**Comment by mohamed82008** [comment]
I installed arrayfire on /home/username does it have to be in /usr/local or some other specific folder?

**Comment by gaika** [comment]
you have to add the path to the missing libraries to the LD_LIBRARY_PATH so they are found.

**Comment by mohamed82008** [comment]
Lol I know the problem, I wrote LD_PATH_LIBRARY in the bashrc when it should be LD_LIBRARY_PATH :)
