### ISSUE TITLE
In-place BLAS commands?

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaComputing/ArrayFire.jl#17]
Are the BLAS commands `axpy!`, `scal!`, etc. implemented?

**Comment by ranjanan** [comment]
No, the BLAS is abstracted out in this library. What you could probably do is to use [`CUBLAS.jl`](https://github.com/JuliaGPU/CUBLAS.jl) for those functions.

**Comment by dlfivefifty** [comment]
But does CUBLAS work with AFArrays?

**Comment by ranjanan** [comment]
Not currently, but it shouldn't be hard to interface with all the others (CUBLAS, etc). I think it'd be nice to have them work with each other and be compatible. Shall I open a separate issue for it and close this one?

**Comment by dlfivefifty** [comment]
OK sounds good!  It’ll probably be very useful to have all the in-place variants to help save GPU memory. 

(I’m really excited about this package! I think it’s going to help speed up certain tasks in ApproxFun a lot.)

**Comment by ranjanan** [comment]
Sure. Thank you for your suggestions, and it would be nice to help other packages speed things up. :)

**Comment by ViralBShah** [comment]
Great idea to be able to use AF Arrays with CUBLAS.jl.
