### ISSUE TITLE
Parallel for-loop

### ISSUE THREAD

**Issue by hayatoikoma** [JuliaComputing/ArrayFire.jl#178]
I have a for-loop that I want to execute in parallel with ArrayFire, but I am wondering what is the best way to achieve this. For example, I have a reduction:
```
x = randn(N)
v = 0.0
for i in 1:N
    v += f(x[i]) // Some computation with ArrayFire
end
```
I guess it is executed sequentially but would like to make it parallel. I think this problem boils down to how to handle `gfor` in ArrayFire in Julia. I read the discussion in #104 but am wondering what is the current state after the major revision of ArrrayFire.jl. How should I write to make it parallel?

**Comment by gaika** [comment]
Try `sum(f.(x), 1)` - reductions work reasonably fast, especially if you don't reduce to `AFArray` and not a scalar. There is no general purpose `reduce` unfortunately.

**Comment by hayatoikoma** [comment]
I see. If I write it in that way, does it compute in parallel?

What about the case where I don't `reduce`?
For example,
```
x = randn(N)
A = Vector{Array}(N)
for i in 1:N
    A[i] = f(x[i]) // Some computation with ArrayFire and `f` returns `AFArray`
end
```

Is it better to write something like
```
x = randn(N)
B = Vector{AFArray}(N)
for i in 1:N
    B[i] = f(x[i]) // Some computation with ArrayFire and `f` returns `AFArray`
end
A = convert(Vector{Array}, B)
```
?

**Comment by pavanky** [comment]
@hayatoikoma You should be able to do `B = f(x)`.

**Comment by gaika** [comment]
ArrayFire can compute most of the functions in parallel if the inputs are of the same size and you stack them along an extra dimension. So Vector{AFAray{Float32,2}} should be AFArray{Float32,3} then f(x) would do the trick.

**Comment by hayatoikoma** [comment]
@pavanky I am not sure what you mean. Doesn't it depend on what `f` returns?

@gaika 
Do you mean
```
x = randn(K)
B = AFArray{Float32,3}(I,J,K)
for k in 1:K
    B[:,:,k] .= f(x[k]) // Some computation with ArrayFire and `f` returns `AFArray{Float32,3}`
end
A = Array(B)
```
? Does `x` need to be `AFArray`?

**Comment by gaika** [comment]
just drop `for` loop and covert x to AFArray, then make sure all operations inside `f` are aware of x being AFArray and not a scalar. Then you can just make `B = f(x)`. Would probably require some tweaking in `f`

**Comment by hayatoikoma** [comment]
I see. So, the key is to make everything from `Array` to `AFArray` before a for-loop.
Thank you!
