### ISSUE TITLE
Fast version of `AFArray(collect(1.0f0:10))`?

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaComputing/ArrayFire.jl#18]
Not sure if this is possible to do directly on the GPU, but I want to create a vector containing 1.0f0:10.  

Any ideas?  I think if this is possible to do efficiently, then an override of `AFArray(::Range)` would also make sense.  (Creating it on the CPU and copying is really slow...)

**Comment by ranjanan** [comment]
You can do this: `ArrayFire.range(AFArray{Float32}, 10)` to get a vector from 0 to 9 `Float32`s.

**Comment by ranjanan** [comment]
Does this work for you? Can I close this please?

**Comment by dlfivefifty** [comment]
Yep!
