### ISSUE TITLE
`isfinite` and `ifelse` for ArrayFire

### ISSUE THREAD

**Issue by EthanAnderes** [JuliaComputing/ArrayFire.jl#180]
Is it possible to get `isfinite` and `ifelse` working for ArrayFire arrays? In particular, I would like to get the following code to work.

```
a = rand(Float32, 100, 100)
b = rand(Complex{Float32}, 100, 100)
a[1] = Inf
a[2] = -Inf
a[3] = NaN

b[1] = Inf + im * 0
b[2] = 0 + im * Inf
b[3] = NaN + im * Inf

a = AFArray(a)
b = AFArray(b)
ifelse.(isfinite.(a), a, 0)  #<--- this line appears to give problems
ifelse.(isfinite.(b), a, 0)  #<--- this line appears to give problems
```

**Comment by gaika** [comment]
it should be an easy fix: you can use `isinf` and `select` as a workaround. If you have time, maybe you can do it in a PR?

**Comment by EthanAnderes** [comment]
I can give a PR a shot, but I might need a pointer or two since I'm completely unfamiliar with the internals of ArrayFire.jl or ArrayFire in general. 

Yeah, `isinf` could work but would need to be combined with `isnan` since `!isinf(NaN) == true` but what I want is `isfinite(NaN) == false`. Also, not quite sure how to use `select` in place of `ifelse` ... perhaps to replace `NaN` with `Inf`, then sort via select? Anyway, no rush, just trying to figure out how to use broadcasting to replace values on an `AFArray` given a bit mask (BTW: also tried broadcasting the ternary operator `_ ? _ : _` but couldn't get that to work either).
