### ISSUE TITLE
Support of conversion from SubArray to AFArray

### ISSUE THREAD

**Issue by hayatoikoma** [JuliaComputing/ArrayFire.jl#190]
I guess the conversion is intentionally restricted between `Array` and `AFArray`, and the conversion from `SubArray` of `Array` to `AFArray` is currently not supported. As far as I checked, `convert_array` works on it. Is there a safe way to add its conversion?

**Comment by gaika** [comment]
I do not see a more efficient way than to convert it to `Array` first

**Comment by hayatoikoma** [comment]
I see. Then, would it be better to add something like `(::Type{ArrayFire.AFArray}){T,N,I,L}(a::SubArray{T,N,Array{T,N},I,L}) = ArrayFire.convert_array(Array(a))`? Or is it better to leave it as it is?

**Comment by hayatoikoma** [comment]
Thank you for adding the feature!
I wasn't sure if it was okay to assume that `SubArray` of any parent is expected to have `Array` method.

**Comment by gaika** [comment]
It is not, but in most practical cases it works.
