### ISSUE TITLE
trivial install suggestion

### ISSUE THREAD

**Issue by iwelch** [JuliaComputing/ArrayFire.jl#193]
would it make sense, upon Pkg.add(), to check and warn the user if there are no underlying libraries (liba) installed, and tell him to visit your webpage for more instructions?

I know how to do this.  I just think it would be nicer.

**Comment by gaika** [comment]
Even better if Pkg.build() can install it for you. PR?

**Comment by iwelch** [comment]
that would be real work...too many moving parts for you to worry about this, too.  but the warning message is cheap.

**Comment by stillyslalom** [comment]
The [Homebrew/science](https://github.com/Homebrew/homebrew-science) repo was deprecated. Try `brew install brewsci/science/arrayfire`.

**Comment by gaika** [comment]
v3.3.2 is too old, can you add PR with proper installation instructions for the most recent version of ArrayFire?
