### ISSUE TITLE
Failed to load dynamic library

### ISSUE THREAD

**Issue by aw2018** [JuliaComputing/ArrayFire.jl#197]
I got the following error after installed the binary ArrayFire-v3.5.1_Linux_x86_64.sh and exported export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/user1/software/arrayfire/lib. What was missed.wrong? 

julia> using ArrayFire
ERROR: InitError: ArrayFire Error (501) : Failed to load dynamic library. 
Error in af_err unified::AFSymbolManager::call(const char*, CalleeArgs ...) [with CalleeArgs = {}]
In file src/api/unified/symbol_manager.hpp:67
Failed to load dynamic library. See http://www.arrayfire.com/docs/unifiedbackend.htm for instructions to set up environment for Unified backend.

**Comment by gaika** [comment]
Do the examples from ArrayFire work? Do you see `libaf*` when you do `ldd examples/benchmarks/blas_cuda`?

**Comment by aw2018** [comment]
@gaika 
ldd: examples/benchmarks/blas_cuda: No such file or directory
only three files in benchmarks/  blas.cpp  cg.cpp  fft.cpp  pi.cpp

**Comment by gaika** [comment]
Find where `libaf*.so` lives, make sure it is the directory that you add to LD_LIBRARY_PATH, then make sure it has all dependencies installed with `ldd libaf*.so`. Try to compile and run examples from ArrayFire.

**Comment by aw2018** [comment]
@gaika 
libaf*.so in lib/ and it was exported in LD_LIBRARY_PATH. 
Not sure what deps are? I used binary file instead of building from source

**Comment by gaika** [comment]
You should see something like this:

`ldd /usr/lib/libafcuda.so
	linux-vdso.so.1 =>  (0x00007ffd8df42000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f7428aba000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f74288b6000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f74286ad000)
	libnvrtc.so.9.1 => /usr/local/cuda-9.1/targets/x86_64-linux/lib/libnvrtc.so.9.1 (0x00007f7426f81000)
	libcublas.so.9.1 => /usr/local/cuda-9.1/targets/x86_64-linux/lib/libcublas.so.9.1 (0x00007f742385d000)
	libcufft.so.9.1 => /usr/local/cuda-9.1/targets/x86_64-linux/lib/libcufft.so.9.1 (0x00007f741c36f000)
	libcusolver.so.9.1 => /usr/local/cuda-9.1/targets/x86_64-linux/lib/libcusolver.so.9.1 (0x00007f7416bfa000)
	libcusparse.so.9.1 => /usr/local/cuda-9.1/targets/x86_64-linux/lib/libcusparse.so.9.1 (0x00007f7413526000)
	libcuda.so.1 => /usr/lib64/nvidia/libcuda.so.1 (0x00007f7412985000)
	libgomp.so.1 => /lib64/libgomp.so.1 (0x00007f741275f000)
	libfreeimage.so.3 => /lib64/libfreeimage.so.3 (0x00007f74124e4000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f74121db000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f7411ed9000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f7411cc3000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f74118ff000)
	/lib64/ld-linux-x86-64.so.2 (0x000055bde31e8000)
	libnvidia-fatbinaryloader.so.390.30 => /usr/lib64/nvidia/libnvidia-fatbinaryloader.so.390.30 (0x00007f74116b3000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f741149c000)
	libmng.so.1 => /lib64/libmng.so.1 (0x00007f741122a000)
	libpng15.so.15 => /lib64/libpng15.so.15 (0x00007f7410fff000)
	libtiff.so.5 => /lib64/libtiff.so.5 (0x00007f7410d8a000)
	libjpeg.so.62 => /lib64/libjpeg.so.62 (0x00007f7410b35000)
	libopenjpeg.so.1 => /lib64/libopenjpeg.so.1 (0x00007f7410911000)
	libIlmImf.so.7 => /lib64/libIlmImf.so.7 (0x00007f7410648000)
	libImath.so.6 => /lib64/libImath.so.6 (0x00007f7410436000)
	libHalf.so.6 => /lib64/libHalf.so.6 (0x00007f74101f3000)
	libIex.so.6 => /lib64/libIex.so.6 (0x00007f740ffd3000)
	libIexMath.so.6 => /lib64/libIexMath.so.6 (0x00007f740fdce000)
	libIlmThread.so.6 => /lib64/libIlmThread.so.6 (0x00007f740fbc7000)
	libjbig.so.2.0 => /lib64/libjbig.so.2.0 (0x00007f740f9ba000)
`

Make sure there are no "not found" libraries, if there are, find them and add them to your library path. Most likely you have one or more of them missing.

**Comment by aw2018** [comment]
@gaika 
I typed ldd libafcuda.so and got the following, the only one "libglfw.so.3 => not found". Where should it locate?

	linux-vdso.so.1 =>  (0x00007fff1cbff000)
	libcudart.so.8.0 => /public/apps/cuda/8.0/lib64/libcudart.so.8.0 (0x00007f77ab91e000)
	libcublas.so.8.0 => /public/apps/cuda/8.0/lib64/libcublas.so.8.0 (0x00007f77a8e85000)
	libcufft.so.8.0 => /public/apps/cuda/8.0/lib64/libcufft.so.8.0 (0x00007f77a0036000)
	libcusparse.so.8.0 => /public/apps/cuda/8.0/lib64/libcusparse.so.8.0 (0x00007f779d51b000)
	libcusolver.so.8.0 => /public/apps/cuda/8.0/lib64/libcusolver.so.8.0 (0x00007f7799fac000)
	libnvrtc.so.8.0 => /public/apps/cuda/8.0/lib64/libnvrtc.so.8.0 (0x00007f7798b8f000)
	libcuda.so.1 => /usr/lib64/libcuda.so.1 (0x00007f779818a000)
	libforge.so.1 => /home/awang1/software/arrayfire/lib/libforge.so.1 (0x00007f77972ca000)
	libGL.so.1 => /usr/lib64/libGL.so.1 (0x00007f779703a000)
	libstdc++.so.6 => /public/apps/gcc/5.1.0/lib64/libstdc++.so.6 (0x00007f7796cad000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f7796a28000)
	libgomp.so.1 => /public/apps/gcc/5.1.0/lib64/libgomp.so.1 (0x00007f7796807000)
	libgcc_s.so.1 => /public/apps/gcc/5.1.0/lib64/libgcc_s.so.1 (0x00007f77965f1000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f77963d3000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f779603f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f77dcd8f000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f7795e3b000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f7795c32000)
	libnvidia-fatbinaryloader.so.375.39 => /usr/lib64/libnvidia-fatbinaryloader.so.375.39 (0x00007f77959e6000)
	libfontconfig.so.1 => /usr/lib64/libfontconfig.so.1 (0x00007f77957af000)
	libglfw.so.3 => not found
	libX11.so.6 => /usr/lib64/libX11.so.6 (0x00007f7795472000)
	libXext.so.6 => /usr/lib64/libXext.so.6 (0x00007f779525f000)
	libGLX.so.0 => /usr/lib64/libGLX.so.0 (0x00007f779502f000)
	libGLdispatch.so.0 => /usr/lib64/libGLdispatch.so.0 (0x00007f7794d46000)
	libfreetype.so.6 => /usr/lib64/libfreetype.so.6 (0x00007f7794aa8000)
	libexpat.so.1 => /lib64/libexpat.so.1 (0x00007f7794880000)
	libxcb.so.1 => /usr/lib64/libxcb.so.1 (0x00007f7794661000)
	libXau.so.6 => /usr/lib64/libXau.so.6 (0x00007f779445e000)

**Comment by aw2018** [comment]
@gaika 
I typed ldd libafcuda.so and got the following, the only one "libglfw.so.3 => not found". Where should it locate? thanks.

	linux-vdso.so.1 =>  (0x00007fff1cbff000)
	libcudart.so.8.0 => /public/apps/cuda/8.0/lib64/libcudart.so.8.0 (0x00007f77ab91e000)
	libcublas.so.8.0 => /public/apps/cuda/8.0/lib64/libcublas.so.8.0 (0x00007f77a8e85000)
	libcufft.so.8.0 => /public/apps/cuda/8.0/lib64/libcufft.so.8.0 (0x00007f77a0036000)
	libcusparse.so.8.0 => /public/apps/cuda/8.0/lib64/libcusparse.so.8.0 (0x00007f779d51b000)
	libcusolver.so.8.0 => /public/apps/cuda/8.0/lib64/libcusolver.so.8.0 (0x00007f7799fac000)
	libnvrtc.so.8.0 => /public/apps/cuda/8.0/lib64/libnvrtc.so.8.0 (0x00007f7798b8f000)
	libcuda.so.1 => /usr/lib64/libcuda.so.1 (0x00007f779818a000)
	libforge.so.1 => /home/user1/software/arrayfire/lib/libforge.so.1 (0x00007f77972ca000)
	libGL.so.1 => /usr/lib64/libGL.so.1 (0x00007f779703a000)
	libstdc++.so.6 => /public/apps/gcc/5.1.0/lib64/libstdc++.so.6 (0x00007f7796cad000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f7796a28000)
	libgomp.so.1 => /public/apps/gcc/5.1.0/lib64/libgomp.so.1 (0x00007f7796807000)
	libgcc_s.so.1 => /public/apps/gcc/5.1.0/lib64/libgcc_s.so.1 (0x00007f77965f1000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f77963d3000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f779603f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f77dcd8f000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f7795e3b000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f7795c32000)
	libnvidia-fatbinaryloader.so.375.39 => /usr/lib64/libnvidia-fatbinaryloader.so.375.39 (0x00007f77959e6000)
	libfontconfig.so.1 => /usr/lib64/libfontconfig.so.1 (0x00007f77957af000)
	libglfw.so.3 => not found
	libX11.so.6 => /usr/lib64/libX11.so.6 (0x00007f7795472000)
	libXext.so.6 => /usr/lib64/libXext.so.6 (0x00007f779525f000)
	libGLX.so.0 => /usr/lib64/libGLX.so.0 (0x00007f779502f000)
	libGLdispatch.so.0 => /usr/lib64/libGLdispatch.so.0 (0x00007f7794d46000)
	libfreetype.so.6 => /usr/lib64/libfreetype.so.6 (0x00007f7794aa8000)
	libexpat.so.1 => /lib64/libexpat.so.1 (0x00007f7794880000)
	libxcb.so.1 => /usr/lib64/libxcb.so.1 (0x00007f7794661000)
	libXau.so.6 => /usr/lib64/libXau.so.6 (0x00007f779445e000)

**Comment by gaika** [comment]
you can build it from source without graphics, or install `glfw3` on your system.
