### ISSUE TITLE
Support of A_mul_B!

### ISSUE THREAD

**Issue by hayatoikoma** [JuliaComputing/ArrayFire.jl#199]
I am currently trying to perform eigendecomposition on a `AFArray`. 

To use Julia's `eigs`,  some of basic functions (`size`, `issymmetric`, `eltype`,  `A_mul_B!`) have to be duck typed for custom-typed array. While it wouldn't make sense for `AFArray` to support `issymmetric`, it would be great to support `A_mul_B!` as ArrayFire supports it.

~~I have tried to wrap `af_matmul` to implement `A_mul_B!`, but I have been getting `ReadOnlyMemoryError()` and am not sure what I should do. Would you help me implementing this?~~

Ah, sorry. This was my misunderstanding. I thought the output can be pre-allocated when we call `af_matmul`.

But, if we implement it in this way, is `A * B` making an extra array? Or is it directly writing over `y`?
```julia
y = zeros(AFArray, 10, 10)
A = rand(AFArray, 10, 10)
B = rand(AFArray, 10, 10)
y .= A * B
```

**Comment by gaika** [comment]
ArrayFire is using JIT so it might be or might be not allocating memory for the operation. In this specific case A*B is allocating memory, so .= is not helping much
