### ISSUE TITLE
Not finding git@github.com:JuliaComputing/ArrayFire.jl.git

### ISSUE THREAD

**Issue by arsenal9971** [JuliaComputing/ArrayFire.jl#202]
When trying to generate a random ArrayFire array with the command `AFArray(zeros(Float32,10,10))` I get the following error

> AFArray: Error showing value of type ArrayFire.AFArray{Float32,2}:

> ERROR: ccall: could not find function af_is_sparse in library libaf

In this case I am using Julia 0.6.0. This does not happen with Julia 0.5.x

**Comment by gaika** [comment]
update your arrayfire version, is_sparse is relatively new
