### ISSUE TITLE
ArrayFire replace() support

### ISSUE THREAD

**Issue by LeMinaw** [JuliaComputing/ArrayFire.jl#209]
As far as I know, ArrayFire's `replace()` function is not provided by ArrayFire.jl.

[http://arrayfire.org/docs/group__data__func__replace.htm](url)

Adding it would be quite convenant for doing conditional tests.

Is there any other way to mimic this behaviour?

Somethink like broadcasting a ternary operator should do the trick, but I can't get it to work for now.

**Comment by gaika** [comment]
Take a look at wrap.jl:

```
function replace(a::AFArray,cond::AFArray,b::AFArray)
function replace(a::AFArray,cond::AFArray,b::Real)
```

**Comment by LeMinaw** [comment]
Sorry, I should have looked a little better.
I'll add it to the docs then.

**Comment by gaika** [comment]
If you are going to change the docs, please update all other functions too. Or at least mention that all arrayfire functions are supported.
