### ISSUE TITLE
norm does not respect type

### ISSUE THREAD

**Issue by rveltz** [JuliaComputing/ArrayFire.jl#211]
Hi,

I have the following issue

```julia
a = AFArray(zeros(Float32,10))
typeof(norm(a))
```

which returns `Float64`. Can it be easily solved?

Thank you,

Best regards

**Comment by gaika** [comment]
In the latest version for v0.7 it is fixed:
```
julia> a = AFArray(zeros(Float32,1))
AFArray: 1-element Array{Float32,1}:
 0.0
julia> typeof(norm(a))
Float32
```
You can make the same fix for the version that you have:
https://github.com/JuliaComputing/ArrayFire.jl/blob/master/src/util.jl#L330
```
norm(a::AFArray{T}) where T = T(norm(a, AF_NORM_EUCLID, 0, 0))
```

**Comment by rveltz** [comment]
Thank you!
