### ISSUE TITLE
Some operations causes Intel MKL FATAL ERROR

### ISSUE THREAD

**Issue by NoelAraujo** [JuliaComputing/ArrayFire.jl#215]
Some  operations causes ArrayFire to crash with the following message:

> Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so.

The mentioned files are indeed inside the installation folder on ArrayFire. However, this error happens with `det`, `inv` for example, but do not with `sin` or `>`.

I've run ArrayFire examples related with those operations in C++, and they work. 
For reference. I'm using ubuntu 16.04, this error happens with Julia 0.6.4 and 0.7.0
```
julia> using ArrayFire
ArrayFire v3.6.1 (OpenCL, 64-bit Linux, build 4fcd0dd)
[0] AMD: gfx900, 8176 MB
```
Other people also found this error on [Julia discourse](https://discourse.julialang.org/t/computing-eigenvalues-eigenvectors-using-gpu/12396/7)

**Comment by NoelAraujo** [comment]
At Ubuntu 18.04, the same occurs with Julia 1.0, and now Atom  displays some Warnings that may help
```
using ArrayFire
[ Info: Precompiling ArrayFire [b19378d9-d87a-599a-927f-45f220a2c452]
WARNING: could not import SparseArrays.full into ArrayFire
WARNING: could not import Base.atan2 into ArrayFire
WARNING: could not import Base.select into ArrayFire
WARNING: could not import LinearAlgebra.gradient into ArrayFire
WARNING: could not import LinearAlgebra.chol into ArrayFire
WARNING: could not import LinearAlgebra.vecnorm into ArrayFire
WARNING: could not import Base.Ac_mul_B into ArrayFire
WARNING: could not import Base.At_mul_B into ArrayFire
WARNING: could not import Base.A_mul_Bc into ArrayFire
WARNING: could not import Base.Ac_mul_Bc into ArrayFire
WARNING: could not import Base.A_mul_Bt into ArrayFire
WARNING: could not import Base.At_mul_Bt into ArrayFire
WARNING: could not import Base.ctranspose into ArrayFire
WARNING: could not import Base.find into ArrayFire
WARNING: could not import Base.select into ArrayFire
WARNING: could not import Random.srand into ArrayFire
ArrayFire v3.6.1 (OpenCL, 64-bit Linux, build 4fcd0dd)
[0] AMD: gfx900, 8176 MB
```

**Comment by NoelAraujo** [comment]
OK, I've got the solution.
This problem already is know on python+anaconda on [stackoverflow](https://stackoverflow.com/questions/36659453/intel-mkl-fatal-error-cannot-load-libmkl-avx2-so-or-libmkl-def-so).

In summary, we need to load some paths with `LD_PRELOAD`. In my computer,  `libmkl_avx2.so` and `libmkl_def.so` are in `/opt/arrayfire/lib/`. 

Then I should use:
 `export LD_PRELOAD=/opt/arrayfire/lib/libmkl_avx2.so:/opt/arrayfire/lib/libmkl_def.so` 

**However**, those files need `libmkl_sequential.so` and `libmkl_core.so`. 
* `libmkl_core.so` is included on ArrayFire folder, so just use the same path as the others
* `libmkl_sequential.so` is not included with ArrayFire, but it does with Anaconda3 - in my computer is on the folder `/opt/anaconda3/lib/`

The final solution was : 
**` > export LD_PRELOAD=/opt/arrayfire/lib/libmkl_avx2.so:/opt/arrayfire/lib/libmkl_def.so:/opt/anaconda3/lib/libmkl_sequential.so:/opt/arrayfire/lib/libmkl_core.so`**

Then, after running Julia, operations like `inv`, `det` and `qr` are working

**Comment by Cyvadra** [comment]
still not working for me... I'm sure I've dealt with libmkl*.so, and ran ldconfig...

Julia Version 1.2.0-DEV.28
Commit a0b7a76103 (2018-12-18 02:23 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2651 v2 @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, ivybridge)

ArrayFire v3.6.2 (OpenCL, 64-bit Linux, build dc38ef1)
[0] NVIDIA: GeForce GTX TITAN Black, 6081 MB
