### ISSUE TITLE
Add precompile back for version 0.7?

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaComputing/ArrayFire.jl#218]
Precompile is not needed in 1.0, as it's the default, right, but does it do any harm?

If I recall it was dropped in 1.0, not 0.7, so is it premature to drop, since 0.7 still supported?

https://github.com/JuliaComputing/ArrayFire.jl/commit/80d7805644f8e8bb7624d98cac19946b7638ae09

I see older ArrayFire mentioned here:
https://github.com/svaksha/Julia.jl/blob/master/Super-Computing.md

I guess it could be deleted there...

**Comment by gaika** [comment]
https://github.com/JuliaLang/julia/blob/master/HISTORY.md

```Module pre-compilation is now the default for code loading. Adding a __precompile__() declaration is no longer necessary, although __precompile__(false) can still be used to opt-out ([#26991]).```
