### ISSUE TITLE
ArrayFire cannot be added on Julia 1.0

### ISSUE THREAD

**Issue by manipadmeom** [JuliaComputing/ArrayFire.jl#219]
] add ArrayFire
 
ERROR: Git repository not found at 'ArrayFire'

**Comment by gaika** [comment]
What happens when you try to install any other package? Are you behind a firewall?

**Comment by manipadmeom** [comment]
No, it seems I can download other packages without problems

add NNlib
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `~/.julia/environments/v1.0/Project.toml`
  [872c559c] + NNlib v0.4.2
  Updating `~/.julia/environments/v1.0/Manifest.toml`
 [no changes]

**Comment by manipadmeom** [comment]
Well probably that is the case. I have currently both Julia 0.64 and 1.0 on my machine so there could be some kind of conflict. I will try your advice and report back,

**Comment by manipadmeom** [comment]
In the end I had to delete Julia and download it again. It seems there was a problem with the installation. But now is working just fine. Thanks!
