### ISSUE TITLE
ArrayFire.jl hangs

### ISSUE THREAD

**Issue by andreasnoack** [JuliaComputing/ArrayFire.jl#23]
I trying out ArrayFire.jl on a cluster with GPUs. Unfortunately, I don't have access to the CUDA Toolkit so I downloaded the compiled version of ArrayFire instead. I think the installation succeeded but I don't think I can compile the examples in ArrayFire without CUDA so I'm not completely sure. (The GPU driver should work, e.g. in MATLAB). I can load ArrayFire.jl but when running a command it just hangs, e.g.

```jl
[anoack@gpu-1 ~]$ julia/julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.6-pre+28 (2016-04-22 00:59 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 022917e* (40 days old release-0.4)
|__/                   |  x86_64-redhat-linux

julia> using ArrayFire

julia> A = rand(AFArray{Float64}, 100, 100)
^CERROR: InterruptException:
 in af_randu at /home/gridsan/anoack/.julia/v0.4/ArrayFire/src/wrap.jl:1033
 in rand at /home/gridsan/anoack/.julia/v0.4/ArrayFire/src/create.jl:7
```
Any ideas about how to debug this?

**Comment by ranjanan** [comment]
I think you need to have [CUDA installed on your system](http://arrayfire.org/docs/installing.htm#Debian) to use ArrayFire. I don't think the binary is working in that case. 

Can you check if the other backends are working? What does `getAvailableBackends()` give you?

**Comment by ViralBShah** [comment]
It is not clear one has to do this in the README. Perhaps worth documenting how to get CUDA on linux.

**Comment by ranjanan** [comment]
Sure, will include that.
