### ISSUE TITLE
How to run the benchmarks?

### ISSUE THREAD

**Issue by ViralBShah** [JuliaComputing/ArrayFire.jl#24]
Is there a way to run the benchmark and generate the graph you have in the README? Would be nice to have a script that does it for all available backends.

**Comment by ranjanan** [comment]
Hey, there's a benchmarks folder with my [benchmark script](https://github.com/JuliaComputing/ArrayFire.jl/blob/master/benchmarks/benchmark.jl). This would generate all the numbers.

**Comment by ranjanan** [comment]
It assumes the CUDA backend though. Hmm, maybe it's worth updating it to check which backends are available, then benchmark each of them.

**Comment by ViralBShah** [comment]
And document it in the README.
