### ISSUE TITLE
Is it possible to interact ArrayFire with cuBLAS?

### ISSUE THREAD

**Issue by AStupidBear** [JuliaComputing/ArrayFire.jl#26]
Since the native ArrayFire dosen't support low-level BLAS operations like gemm, axpy and symv, it'll be great to glue ArrayFire and cuBLAS together. However, is this feasible?

**Comment by ranjanan** [comment]
The plan is to make ArrayFire compatible with other JuliaGPU packages such as CUBLAS. Ref #19. Once I have something I'll update that thread.
