### ISSUE TITLE
Cannot use ArrayFire in Atom 

### ISSUE THREAD

**Issue by AStupidBear** [JuliaComputing/ArrayFire.jl#28]
I have added ```export LD_LIBRARY_PATH=/usr/local/lib/``` and it works when I use ArrayFire.jl in terminal. However in Atom, I got the following errors:
![image](https://cloud.githubusercontent.com/assets/16422976/15750405/ef55691e-2918-11e6-9f3a-dd51c7fc0aab.png)

**Comment by ranjanan** [comment]
Is Atom looking at a different path as compared to the `LD_LIBRARY_PATH` ? Perhaps @MikeInnes could help?

**Comment by MikeInnes** [comment]
This is probably due to Atom not picking up on environment variables defined in `~/.bash_profile` or similar, since they'll be loaded by the shell. You can get around this either by running atom using the `atom` command in the shell, or simply by adding the variable on the julia side; e.g. with `ENV["LD_LIBRARY_PATH"] = "..."` in your juliarc.jl

**Comment by ranjanan** [comment]
@AStupidBear , open a file called .juliarc.jl in your home directory, and write:
```julia
ENV["LD_LIBRARY_PATH"] = "/usr/local/lib/"
``` 
to it. Atom should be able to load it.

**Comment by AStupidBear** [comment]
Thanks.

**Comment by AStupidBear** [comment]
Thank you. It worksSent from my Huawei Mobile-------- Original Message --------Subject: Re: [JuliaComputing/ArrayFire.jl] Cannot use ArrayFire in Atom  (#28)From: Mike J Innes To: "JuliaComputing/ArrayFire.jl" CC: Yao Lu ,Author This is probably due to Atom not picking up on environment variables defined in ~/.bash_profile or similar, since they'll be loaded by the shell. You can get around this either by running atom using the atom command in the shell, or simply by adding the variable on the julia side; e.g. with ENV["LD_LIBRARY_PATH"] = "..." in your juliarc.jl
