### ISSUE TITLE
Cannot use clamp on AFArray

### ISSUE THREAD

**Issue by AStupidBear** [JuliaComputing/ArrayFire.jl#29]
try this code
```julia
using ArrayFire
# AFArray
af=zeros(AFArray{Float32},10,10);
clamp(af,0.2,0.8)
af[1]
# Julia Array
ju=zeros(10,10);
clamp(ju,0.2,0.8);
ju[1]
```

![image](https://cloud.githubusercontent.com/assets/16422976/15750637/d8f45472-2919-11e6-955a-3329f0d5c404.png)

You can see that the origin of this error lies in that af[1] gives an array not a number.
I could write a function 
```julia
import Base.clamp!
function clamp!(x::AFArray, lo, hi)
    @inbounds for i in length(x)
        x[i] = clamp(Array(x[i])[1], lo, hi)
    end
    x
end
```
However, this will affect performance. Is there a better way to deal with this?

**Comment by ranjanan** [comment]
So there's no `clamp` function defined for an `AFArray`. The library doesn't support that function right now. You're probably getting a weird error possibly because it's a subtype of `AbstractArray` in Base. That last loop simply copies each value to the CPU and perform the operation. No execution is happening on the GPU.

**Comment by ranjanan** [comment]
Not all the standard library in Julia is supported by ArrayFire right now. I think a note on what is supported and what isn't might be useful.

**Comment by pavanky** [comment]
@ranjanan is there anyway it can error out more elegantly ?

**Comment by ranjanan** [comment]
Yeah, I'm thinking about that too.

**Comment by AStupidBear** [comment]
I'm so stupid. 
```julia
import Base.clamp
export clamp
function clamp(x::AFArray, lo, hi)
  max(min(x,hi),lo)
end
```
