### ISSUE TITLE
How can I use function find?

### ISSUE THREAD

**Issue by AStupidBear** [JuliaComputing/ArrayFire.jl#32]
Since ArrayFire dosen't support ```find```, is there any way to get around?
```julia
c=randn(AFArray{Float32},10000000)
find(Array(c).>0);
find(Array(c.>0));
``` 
could do this but it's not efficient.

**Comment by ranjanan** [comment]
Actually the function `find` is supported. I initially thought it behaved like `findnz` but it actually behaves like `find`.
