### ISSUE TITLE
ArrayFire is unreasonably faster than julia!

### ISSUE THREAD

**Issue by AStupidBear** [JuliaComputing/ArrayFire.jl#33]
Look at the following code
```julia
using Devectorize
using ArrayFire

julia(x,y)=x.^4.*y.^3+10.*x.^2
function devectorize(x,y)
  @devec r=x.^4.*y.^3+10.*x.^2
end

x=randn(10000000);y=randn(10000000);
xaf=AFArray(x);yaf=AFArray(y);
julia(x,y);devectorize(x,y);julia(xaf,yaf);
@time a=julia(x,y);@time c=julia(xaf,yaf);@time b=devectorize(x,y);
@assert a==b
@assert a==Array(c)
```
The result is (cpu)
```julia
julia> @time a=julia(x,y);@time c=julia(xaf,yaf);@time b=devectorize(x,y);
  5.534964 seconds (27 allocations: 457.764 MB, 2.95% gc time)
  0.000339 seconds (152 allocations: 4.250 KB)
  4.853867 seconds (8 allocations: 76.294 MB, 0.02% gc time)
```
How could you explain this?

**Comment by ranjanan** [comment]
Could you post the output of `versioninfo()`?

**Comment by SimonDanisch** [comment]
Try this:
```Julia
function getbackend()
    backend = Base.Ref{Cuint}(0)
    ArrayFire.af_get_active_backend(backend)
    backend[]
end
function af_julia(x,y)
    r = x.^4.*y.^3+10.*x.^2
    ArrayFire.af_eval(r)
    ccall((:af_sync, ArrayFire.af_lib), Cint,(Cint,), getbackend())
    r
end
```
on my pc, it's slower then julia (1.8s vs 1.5 vs 0.8 mydevec)

**Comment by AStupidBear** [comment]
@ranjanan 
```julia
julia> versioninfo()
Julia Version 0.4.5
Commit 2ac304d (2016-03-18 00:58 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i3-2367M CPU @ 1.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACK NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by pavanky** [comment]
Arrayfire is non blocking. You need to have a `sync` to make sure all operations are finished. You only need `sync` for benchmarking purposes, do not leave it in for real use cases.

Also, if you are using JIT, you need to run `eval` to make sure the operations are evaluated.

But if you put a `sync` at the end of each function that is going to slow things down. Ideal way to benchmark would be to run the code for n iterations, have `eval` in every iteration, but `sync` only once.

**Comment by SimonDanisch** [comment]
@pavanky, while we're at it, this suggests that you're building up the compute graph lazily and probably are doing some smart scheduling and optimizations.
I guess in Julia, we will have it a bit harder to optimize this case:
```Julia
a = a+b
```
I'm assuming, that you capture and use that information by overloading `=` http://arrayfire.org/docs/group__array__mem__operator__eq.htm ?
Also, how many temporaries will this create:
```Julia
r = x.^4.*y.^3+10.*x.^2
```
just r, or also one for every `operator(a,b)` ?

**Comment by pavanky** [comment]
@SimonDanisch for CUDA and OpenCL, launching a single kernel for each operation is costly. What we do is batch all element wise operations (including all arithmetic operators, math functions, logical operations) into a single kernel, compile it at runtime, cache it and reuse those kernels if a similar tree is seen in the future.

In your expression, the data for `r` is not created until one of the following conditions is met
-  `r.eval()`  (a c++ expression, not sure what it is in Julia)
- `r` is called inside a function that is not JIT. For example `sum(r)` would create the buffer for `r` and then evaluate it.
- If the tree gets too large, we have a way to cut down the tree. We do this to reduce the memory footprint (as the leaves in the tree are almost actual buffers).

**Comment by pavanky** [comment]
BTW whatever I mentioned in my previous comment is available through the C api. We are not doing anything special in C++. (`r.eval()` in C++ is just `af_eval(c)` in the `C` API).

All of lazy evaluation happens within each backend library.

**Comment by SimonDanisch** [comment]
Thanks for the explanation!
As you can see in my sample, `af_eval` is already wrapped :)

> launching a single kernel for each operation is costly

Exactly ;) 
Well, that's great to hear!

@shashi, so things start looking a bit like a fractal when you're using ArrayFire as a backend for ComputeFramework.jl, since it seems to have a fairly similar execution model ;)

**Comment by AStupidBear** [comment]
Thanks to all of you guys!

**Comment by shashi** [comment]
An `@aftime` macro will be handy for interactive time measurements

```
macro aftime(exp...)
           exp1 = quote
               $exp
               af_sync()
           end |> esc
           :(@time $exp1)
end
```
