### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by davidanthoff** [JuliaComputing/ArrayFire.jl#40]
If it doesn't work on Windows, would be great to add one sentence to the README stating so (and saving people time to figure it out themselves).

Longer term it would of course be great if this had first class windows support, i.e. including downloading of the arrayfire binaries via BinDeps etc.

**Comment by ViralBShah** [comment]
The official ArrayFire binaries are behind a login at the moment - so having it via BinDeps would mean building it all ourselves. And I wonder if those include CUDA or not. Currently, even if ArrayFire was built as a library, one would still have to install CUDA by hand.

We should make sure it works on Windows though. What error did you face?

**Comment by davidanthoff** [comment]
I didn't even try it, I just looked at the README and saw install sections for Mac and Linux but not for Windows and then posted this issue :)

This is not a high priority for me at all, I just wanted to play around with this a little.

**Comment by Paulms** [comment]
I try it on Windows and I get an error. Python bindings are working well.

ERROR: LoadError: LoadError: UndefVarError: lib not defined
 in include at boot.jl:261
 in include_from_node1 at loading.jl:320
 in include at boot.jl:261
 in include_from_node1 at loading.jl:320
 in require at loading.jl:259
while loading C:\Users\PaulE\.julia\v0.4\ArrayFire\src\config.jl, in expression starting on line 6
while loading C:\Users\PaulE\.julia\v0.4\ArrayFire\src\ArrayFire.jl, in expression starting on line 5

**Comment by SimonDanisch** [comment]
Try #42 ;)

**Comment by ranjanan** [comment]
PR #42 has been merged, enabling Windows support.
