### ISSUE TITLE
GLFW wasn't able to initalize

### ISSUE THREAD

**Issue by AStupidBear** [JuliaComputing/ArrayFire.jl#41]
What does this mean?

```julia
julia> using ArrayFire

julia> AFArray(zeros(10,10))
ERROR: GLFW wasn't able to initalize
10x10 ArrayFire.AFArray{Float64,2}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
```

**Comment by ranjanan** [comment]
`GLFW` is a graphics library which `arrayfire` uses. Did you build `arrayfire` with GLFW? 

Also, `ArrayFire.jl` doesn't current support graphics using GLFW.

**Comment by pavanky** [comment]
This is a debug message. You can safely ignore it (as long as you don't use arrayfire graphics functionality). If you don't want to see it, put `export AF_DISABLE_GRAPHICS=1` in your environment somewhere.

**Comment by AStupidBear** [comment]
Thanks for your explanations

**Comment by iridiumblue** [comment]
And thanks again.
BTW - can the devs change the wording to "Warning" ?
"Error" is typically meant to indicate a show-stopper.
