### ISSUE TITLE
 matrix multiplication doesn't support bit arrays.

### ISSUE THREAD

**Issue by blairn** [JuliaComputing/ArrayFire.jl#51]
in Julia, matrix multiplication for bits works just fine.

```
julia> x = [1; 2; 3; 4]
4-element Array{Int64,1}:
 1
 2
 3
 4

julia> y = x .>2
4-element BitArray{1}:
 false
 false
  true
  true

julia> x' * y
1-element Array{Int64,1}:
 7
```

with ArrayFire, it doesn't seem to

```
julia> x = AFArray([1; 2; 3; 4])
4-element ArrayFire.AFArray{Int64,1}:
 1
 2
 3
 4

julia> y = x .> 2
4-element ArrayFire.AFArray{Bool,1}:
 false
 false
  true
  true

julia> x' * y
ERROR: "ArrayFire Error (205) : Input types are not the same"
 in af_matmul at C:\Users\Blair\.julia\v0.4\ArrayFire\src\wrap.jl:978

```

weirdly enough, .*s work just fine.

```
julia> x .* y
4-element ArrayFire.AFArray{Int64,1}:
 0
 0
 3
 4
```

Is this a bug? How do I make matrix multiplication to work?

**Comment by ViralBShah** [comment]
BitArrays are not available for ArrayFire, AFAICT.

**Comment by ViralBShah** [comment]
Bool Arrays and bitarrays in Julia are different. I am guessing that bool array multiplication is not available in ArrayFire - but @ranjanan should know.

**Comment by ranjanan** [comment]
Yeah, integer boolean multiplication isn't supported in the `arrayfire` library. `x' * y` descends to a BLAS call in the library, and the call only takes in floats. So you'd have to convert both `x` and `y` to floats before you perform that operation.  
```julia 
x = convert(AFArray{Float32}, x)
y = convert(AFArray{Float32}, y)
x'  *  y
```
