### ISSUE TITLE
getActiveBackend() fails

### ISSUE THREAD

**Issue by lruthotto** [JuliaComputing/ArrayFire.jl#54]
On my Mac using julia 0.4.6 I'm getting the following error

```
julia> using ArrayFire
julia> Pkg.test("ArrayFire")
INFO: Testing ArrayFire
INFO: ArrayFire tests passed
julia> getActiveBackend()
ERROR: ccall: could not find function af_get_active_backend in library libaf
 in af_get_active_backend at /Users/lruthot/.julia/v0.4/ArrayFire/src/wrap.jl:955
 in getActiveBackend at /Users/lruthot/.julia/v0.4/ArrayFire/src/backend.jl:14
```

**Comment by pavanky** [comment]
This was a feature that was added in v3.3.0. I don't think brew updated arrayfire to 3.3 yet.

Meanwhile,  I think @ranjanan is in the process of erroring out properly.

@ranjanan btw, for older versions you can hack together the same functionality by passing an empty array to af_get_backend_id

**Comment by ranjanan** [comment]
Appropriate error message add by e66ec47e0456f28498f8fc7afc6063742eb8b5c9. 

@pavanky Thanks, will look into that hack.
