### ISSUE TITLE
Getting an arbitrary sub-array

### ISSUE THREAD

**Issue by esproff** [JuliaComputing/ArrayFire.jl#56]
Is there an ability to get specific sub-arrays from an AFArray?

I know you can use ranges to get contiguous or regularly spaced sub-arrays, but I get an error when I try to get an arbitrary sub-array using a vector of coordinates, for instance if I had an AFArray `A` which was 10x10 and I wanted the columns `[1,2,9]`, I would normally do

```
A[:,[1,2,9]]
```

but this doesn't work.  Looking at the list of indexing functions on the ArrayFire documentation website I believe the `cols` function is what I want, has this not be wrapped yet, or is there a way of doing this in Julia?

**Comment by ranjanan** [comment]
@esproff `A[:, AFArray([1,2,9])]` would work. You need to convert the Julia Array into an `AFArray` to index other `AFArray`s. 

As for wrapping `cols`, I wonder if this indexing functionality generally works for most users, and whether it's necessary to give users that function, given that we don't have a similar function in Julia.
