### ISSUE TITLE
How to run loops efficiently?

### ISSUE THREAD

**Issue by esproff** [JuliaComputing/ArrayFire.jl#57]
So this might be related to [#27](https://github.com/JuliaComputing/ArrayFire.jl/issues/27), but the only way I seem to be able to run loops which don't degrade in performance is to call `gc()` after every iteration of the loop.  Otherwise the more loops I go through the more things slow down.  For instance:

```
function f()
    r = AFArray(zeros(Float32, 100, 100000))
    a = AFArray(rand(Float32, 100, 100000))
    for d in 1:100:90000
        r[:,d:d+99] = a[:,d:d+99] .* a[:,d:d+99]
    end
    nothing
end

for _ in 1:15
    @time f()
end
```

I have to garbage collect in the for-loop inside `f` in order to avoid increasingly degraded performance the more the more times I run `f`, and since running garbage collection so often slows things down immensely, I'm not really sure what to do.

**Comment by ranjanan** [comment]
Other than the need to run `gc()` every so often, a major amount of time might be spent in indexing. 

The problem right now is that the Julia garbage collector is not sensitive to the GPU memory, and is only aware of the CPU memory. ArrayFire itself has its own memory manager that clears garbage on its own terms. This results in memory not being freed in a timely manner, and you having to manually trigger the gc. 

The solution is to make the gc sensitive to the amount of GPU memory. @Keno and @JeffBezanson had some thoughts on this.

**Comment by esproff** [comment]
Is indexing performance something that can be significantly improved?  Or is this an inherent limitation of GPU programming?

**Comment by SimonDanisch** [comment]
>Is indexing performance something that can be significantly improved? Or is this an inherent limitation of GPU programming?

Well Indexing GPU memory from the CPU is of course an inherent limitation, as long as they don't share the same memory space.
What we can do is to execute the loop on the GPU, which you can by writing your own Kernels.
You shuld be soon able to write these  kernels in Julia: https://github.com/JuliaGPU/CUDAnative.jl
It's actually working fairly well already, if you're willing to build Julia yourself!

**Comment by esproff** [comment]
@SimonDanisch,

Can this also be done on on OpenCL.jl?  (I don't have an NVIDIA chip).  Also I have only a passing familiarity with C/C++, is that enough to write my own kernels?  (sorry for all the questions).

**Comment by SimonDanisch** [comment]
We hope to naturally extend the same approach to OpenCL :) Yeah, simple kernels should be straight forward to write... Main entry burden are indexing behaviour and calling the kernel. Just look at the examples in OpenCL.jl! I'm not sure if it's wrapped already, but it should be straight forward to call the kernels on ArrayFire arrays!

**Comment by esproff** [comment]
@SimonDanisch,

Thanks!

**Comment by ranjanan** [comment]
@esproff , if you don't mind, could you refer #27 for the gc discussion from here on?

**Comment by esproff** [comment]
@ranjanan,

sure, no problem.
