### ISSUE TITLE
ERROR: ArrayFire Error (401)

### ISSUE THREAD

**Issue by cpierard** [JuliaComputing/ArrayFire.jl#58]
I installed with success ArrayFire in my computer and in Julia, and runned the test and passed whithout problems. Then I tried to follow the Simple Usage steps in readme.md, but when I try to use the constructor `AFArray()` it appears the following error:

``` 
julia> Pkg.build("ArrayFire")

julia> Pkg.test("ArrayFire")
INFO: Testing ArrayFire
INFO: ArrayFire tests passed

julia> a = rand(10, 10);
10x10 Array{Float64,2}:

julia> using ArrayFire

julia> ad = AFArray(a)
ERROR: ArrayFire Error (401) : Double precision not supported for this device
 in convert at /Users/claudiopierard/.julia/v0.4/ArrayFire/src/create.jl:27
 in call at /Users/claudiopierard/.julia/v0.4/ArrayFire/src/create.jl:31
 ```

**Comment by pavanky** [comment]
Some devices do not support double precision in hardware. Especially Intel GPUs.

What device are you testing this on ?

**Comment by cpierard** [comment]
My GPU is an Intel Iris Graphics 6100 1536 MB, and I am using it on a Mac.

**Comment by pavanky** [comment]
Intel does not support double precision on any of their GPUs. The proper error is being returned.

**Comment by cpierard** [comment]
So, there is nothing to do?

**Comment by ranjanan** [comment]
@cpierard You could use single precision for your computations:
```julia
a = rand(Float32, 10, 10)
ad = AFArray(a)
```
If you have a GPU on your system, and you've built ArrayFire with the CUDA backend (check README on how), you can switch to the CUDA backend and use double precision on your GPU.

**Comment by ranjanan** [comment]
Closing this because this is hardware and a note will be added to the README.
