### ISSUE TITLE
Failed to load dynamic library.

### ISSUE THREAD

**Issue by bluehope** [JuliaComputing/ArrayFire.jl#62]
With cuda 8.0 & 1080 I keep seeing this error message.
How could I fix this problem?

julia> setBackend(AF_BACKEND_CPU)
true

julia> setBackend(AF_BACKEND_CUDA)
ERROR: ArrayFire Error (501) : Failed to load dynamic library.
 in af_set_backend at /home/bluehope/.julia/v0.4/ArrayFire/src/wrap.jl:941
 in setBackend at /home/bluehope/.julia/v0.4/ArrayFire/src/backend.jl:68

NVIDIA-Smi
Tue Aug  2 04:10:16 2016
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.35                 Driver Version: 367.35                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 0000:01:00.0      On |                  N/A |
|  7%   48C    P8    15W / 200W |    194MiB /  8112MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      2682    G   /usr/lib/xorg/Xorg                              49MiB |
|    0     25894    C   julia_0.4                                      141MiB |

**Comment by pavanky** [comment]
ArrayFire v3.3 is not built with CUDA 8. You'll need to build the devel branch of arrayfire from source. Considering that it is a devel branch, expect it to be a bit buggy.

Alternatively, you can use the OpenCL backend which doesn't depend on the CUDA toolkit. You'll however not get the peak performance for linear algebra and FFTs.

**Comment by pavanky** [comment]
Keep in mind that 8.0 available right now is still a release candidate and a version of arrayfire will be available with 8.0 once the final version is released.

**Comment by bluehope** [comment]
Thank you for the reply. I've checked ArrayFire versions and OPENCL also.

1. I've used ArrayFire v3.4 & It seems working 
./blas_cuda
```
ArrayFire v3.4.0 (CUDA, 64-bit Linux, build 71da292)
Platform: CUDA Toolkit 8, Driver: 367.35
[0] GeForce GTX 1080, 8113 MB, CUDA Compute 6.1
Benchmark N-by-N matrix multiply
 128 x  128:   300 Gflops
 256 x  256:  1756 Gflops
 384 x  384:  4573 Gflops
 512 x  512:  5613 Gflops
 640 x  640:  6562 Gflops
 768 x  768:  7593 Gflops
 896 x  896:  6989 Gflops
1024 x 1024:  7367 Gflops
1152 x 1152:  7462 Gflops
1280 x 1280:  8335 Gflops
1408 x 1408:  8023 Gflops
1536 x 1536:  8472 Gflops
1664 x 1664:  8163 Gflops
1792 x 1792:  8615 Gflops
1920 x 1920:  8505 Gflops
2048 x 2048:  8573 Gflops
 ### peak 8615.26 GFLOPS

```
2. However the "OPENCL" backend still don't works.

```
julia> setBackend(AF_BACKEND_OPENCL)
ERROR: ArrayFire Error (501) : Failed to load dynamic library.
 in af_set_backend at /home/bluehope/.julia/v0.4/ArrayFire/src/wrap.jl:941
 in setBackend at /home/bluehope/.julia/v0.4/ArrayFire/src/backend.jl:68
```

@pavanky  Would there be another thing that I've missed??
Would there be some problem binding ArrayFire3.4V with Julia? (even without cuda 8.0)
Thank you in advance!

**Comment by pavanky** [comment]
It could potentially be a missing `LD_LIBRARY_PATH`. The examples from the library use `-rpath` during compilation so they work fine.

Can you run `ldd` on `libafcuda.so.3.4.0` and show the output ? (Same with `libafopencl.so.3.4.0` ?)

Can you also show output of `info` when using cpu backend from Julia?

**Comment by bluehope** [comment]
@pavanky Thankyou for your kind support!.

This was my original path setting
```
export PATH=/usr/local/cuda-8.0/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/
```

And I had to add bellow line and it works! (http://arrayfire.org/docs/unifiedbackend.htm)

```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/nvvm/lib64
```
