### ISSUE TITLE
set_device and release_array

### ISSUE THREAD

**Issue by r3tex** [JuliaComputing/ArrayFire.jl#67]
As per the suggestion of ArrayFire folk, I'm posting some questions/answers here.
I built CUDA 8 and ArrayFire on Xenial from source, and a number of symlinks were causing issues during the build. It was probably my own fault. Notably though, I had to add /usr/local/cuda/nvvm/lib64 explicitly to ld.so.conf.d because the installer didn't do that automatically and CUDA just silently failed to load. Two ideas came up in my first minutes of testing:

- Since my machine has 4 GPUs it'd be nice to be able to switch using af_set_device() from julia. For the time being setting the env variable AF_OPENCL_DEFAULT_DEVICE=3 is a workaround.

- memory does run out and it would be nice to have af_release_array()

Thanks for this great package!

**Comment by pavanky** [comment]
@r3tex about the memory running out, try calling `gc()` (Julia's garbage collector) after a few iterations. This releases any dangling references to objects that are no longer in scope.

**Comment by r3tex** [comment]
@pavanky excellent! That thread clears things up.

**Comment by ranjanan** [comment]
@r3tex Thanks for filing this issue. As Pavan must have told you, there's an ongoing discussion with regard to the gc in #27. I've also added some code to let you switch devices in #68. 

Could you do a `Pkg.checkout("ArrayFire", "RA/device")` to check out my branch ( #68 ) and try using the function `setDevice(device_id)`? This should fix the first part of your issue.
