### ISSUE TITLE
config.jl bug

### ISSUE THREAD

**Issue by musm** [JuliaComputing/ArrayFire.jl#69]
https://github.com/JuliaComputing/ArrayFire.jl/blob/master/src/config.jl#L8 
should be pulled out

**Comment by ranjanan** [comment]
Yes, thanks for pointing it out. I'm going to modify this to put it in a try-catch, because [this](https://github.com/JuliaComputing/ArrayFire.jl/blob/master/src/config.jl#L6) is most likely going to break if the library isn't found. The line still needs to go out.
