### ISSUE TITLE
sync() barrier in BlackScholes example?

### ISSUE THREAD

**Issue by robertfeldt** [JuliaComputing/ArrayFire.jl#71]
The speed comparison seen in the BlackScholes example is very impressive but shouldn't there be a `sync()` barrier before measuring time? Since the sum function is now called outside of the timing it seems to me the timing could be misleading.

**Comment by gaika** [comment]
fixed in #121 , speedup is less insane now :)

**Comment by gaika** [comment]
merged with [v0.1.0](https://github.com/JuliaComputing/ArrayFire.jl/releases/tag/v0.1.0)
