### ISSUE TITLE
Matrix * vector should give vector

### ISSUE THREAD

**Issue by dpsanders** [JuliaComputing/ArrayFire.jl#73]
Currently it gives a matrix.

**Comment by pavanky** [comment]
ArrayFire does not differentiate between "1D matrix" and a vector. I suppose handling this is going to take a lot of work in the Julia Wrapper.

**Comment by gaika** [comment]
I have a fix for it my branch https://github.com/gaika/arrayfire.jl , not very hard.

**Comment by ranjanan** [comment]
@gaika could you submit the fix as a PR please? Thank you very much.

**Comment by gaika** [comment]
merged with [v0.1.0](https://github.com/JuliaComputing/ArrayFire.jl/releases/tag/v0.1.0)
