### ISSUE TITLE
Sparse Arrays?

### ISSUE THREAD

**Issue by LMescheder** [JuliaComputing/ArrayFire.jl#80]
Array fire includes [limited sparse array functionality](http://arrayfire.org/docs/group__sparse__func.htm). Are there any plans to wrap these?

**Comment by pavanky** [comment]
`af_matmul` also supports sparse matrix, dense {matrix, vector} multiplications.

**Comment by ranjanan** [comment]
@LMescheder thanks for reporting this. Support for this will be included ArrayFire very soon.

**Comment by pavanky** [comment]
@ranjanan on a related note, there have been other functions added to arrayfire in 3.4.0:
https://github.com/arrayfire/arrayfire/releases/tag/v3.4.0

If it helps, I made the following issue when adding the necessary functionality to the python wrapper
https://github.com/arrayfire/arrayfire-python/issues/100

**Comment by ranjanan** [comment]
@pavanky Thanks! This is very helpful.

**Comment by pavanky** [comment]
The names in the python wrapper are not identical, but they should provide as a template for the functions to be added.

**Comment by ranjanan** [comment]
@LMescheder I might not be able to get around to adding more functionality to this package for a few weeks. Would you mind putting together a PR to the package? That would be much appreciated. I would help and review as necessary. In general, more contributions to this package would be highly appreciated.

**Comment by bscohen1** [comment]
Has ArrayFire been updated to include sparse array constructors?  I am looking to construct COO sparse arrays and solve a linear system Ax=b.

**Comment by shehzan10** [comment]
@bscohen1 You can use the [sparse()](http://arrayfire.org/docs/group__sparse__func__create.htm) function to create sparse matrices.
Other sparse handling functions can be found [here](http://arrayfire.org/docs/group__sparse__func.htm).

Lastly, you can see sparse usage under the [Conjugate Gradient example](http://arrayfire.org/docs/benchmarks_2cg_8cpp-example.htm).

**Comment by lruthotto** [comment]
I was just wondering, if there is any update on wrapping the sparse functions of ArrayFire into julia code.

**Comment by ranjanan** [comment]
@lruthotto I have been a bit busy with a number of other things. I think @gaika plans on including this functionality in his PR #121.

**Comment by lruthotto** [comment]
Thanks for the update! Looking forward to seeing this in action. @gaika let me know if you need someone to test this functionality. I don't think I can help much with writing the code, but this I can do.

**Comment by gaika** [comment]
@lruthotto - Can you write tests? I have all the wrappers for C code already in place (search for `sparse` in https://github.com/gaika/ArrayFire.jl/blob/master/src/wrap.jl ), it is just a matter of making  sure all types match and maybe adjusting function signatures to be more Julian.

**Comment by gaika** [comment]
Thanks for @lruthotto's initiative and tests it is now possible to convert between `AFArray` and `SparseMatrixCSC` in https://github.com/JuliaComputing/ArrayFire.jl/pull/121

**Comment by gaika** [comment]
merged with [v0.1.0](https://github.com/JuliaComputing/ArrayFire.jl/releases/tag/v0.1.0)
