### ISSUE TITLE
ifft signal not defined error 

### ISSUE THREAD

**Issue by ucanfzh** [JuliaComputing/ArrayFire.jl#81]
Got the following error when run ifft(rand(AFArray{Float64},3,3));
The error occurs only when the argument is of 2 dimensional.  For dimension N=4, the return array is of type Array{Complex{Float64}, N}. 

ERROR: UndefVarError: signal not defined
 in af_ifft2(::Base.RefValue{Ptr{Void}}, ::ArrayFire.AFArray{Float64,2}, ::Float64, ::Int64, ::Int64) at C:\Users\fucai\.julia\v0.5\ArrayFIre\src\wrap.jl:1842
 in #ifft#96(::Float64, ::Int64, ::Int64, ::Function, ::ArrayFire.AFArray{Float64,2}) at C:\Users\fucai\.julia\v0.5\ArrayFIre\src\signal.jl:55
 in ifft(::ArrayFire.AFArray{Float64,2}) at C:\Users\fucai\.julia\v0.5\ArrayFIre\src\signal.jl:54

Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: NT (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, westmere)
 - ArrayFire                     0.0.3

**Comment by ranjanan** [comment]
Thanks for reporting this. That's a bug. I'll push a commit to fix this right now.

**Comment by ucanfzh** [comment]
Thanks for the quick action! 
Also noticed that the code rand(AFArray{Float64}, N1, N2, ...,Np) always returns a 4D array for dimensions larger than 4 (p>4).

**Comment by ranjanan** [comment]
@ucanfzh The array fire library supports a maximum of 4 dimensions, unless I'm mistaken. @pavanky, could you please elaborate on the rationale for this? Thanks.
