### ISSUE TITLE
Anon function unecessary

### ISSUE THREAD

**Issue by musm** [JuliaComputing/ArrayFire.jl#84]
https://github.com/JuliaComputing/ArrayFire.jl/blob/5fd0896b9562925c25372a2392cff83fd9e553b8/src/ArrayFire.jl#L14
no need for the anonymous function
` finalizer(a, af_release_array) `

**Comment by ranjanan** [comment]
@musm I think you're right, but is there any need to change the code now?

**Comment by musm** [comment]
just a pet peeve but yeah
