### ISSUE TITLE
typo in function iota - tdims not defined

### ISSUE THREAD

**Issue by ucanfzh** [JuliaComputing/ArrayFire.jl#86]
https://github.com/JuliaComputing/ArrayFire.jl/blob/master/src/create.jl#L95

variable tdims not defined, should be tile_dims? 
thanks!

**Comment by ranjanan** [comment]
You're right! Thanks for pointing this out!

**Comment by ranjanan** [comment]
Closed by #88

**Comment by ucanfzh** [comment]
Dear Ranjan,

Thank you for your quick actions again!

I'm currently converting my Matlab code to Julia for my research work. The
ArrayFire package is really helpful. I'm still new to Julia. Hopefully, I
can submit pull request one day to help the development of the package,
e.g. plot/graphic support of AFArray (no CPU get involved),
the gfor functionality used in Jacket package for Matlab.
Best regards,
fucai


*Research Professor hiring:*

*http://jobs.workinoptics.com/jobs/8549842/research-assistant-professor*
<https://urldefense.proofpoint.com/v2/url?u=http-3A__jobs.workinoptics.com_jobs_8549842_research-2Dassistant-2Dprofessor&d=CwMFAg&c=AGbYxfJbXK67KfXyGqyv2Ejiz41FqQuZFk4A-1IxfAU&r=bQq4TyrJtV6RT90zTkHZoakTmvm3jdMc65Nfd0Lw5v0&m=S6APoSQNaSuHX-9JCYiUi2Wcptr3HiFRCY3PlrU--DQ&s=N-BuWbb-mXgTZNryOfLDDLWloqOkTc0HH49LI64z2Rk&e=>
*http://careers.aps.org/jobs/8549845/research-assistant-professor*
<https://urldefense.proofpoint.com/v2/url?u=http-3A__careers.aps.org_jobs_8549845_research-2Dassistant-2Dprofessor&d=CwMFAg&c=AGbYxfJbXK67KfXyGqyv2Ejiz41FqQuZFk4A-1IxfAU&r=bQq4TyrJtV6RT90zTkHZoakTmvm3jdMc65Nfd0Lw5v0&m=S6APoSQNaSuHX-9JCYiUi2Wcptr3HiFRCY3PlrU--DQ&s=h8hSEBj6ut6nZnuRuSy0bYa4pfwBGHlrtrv8a35_gD0&e=>
