### ISSUE TITLE
different behavior of AFArray with dimension of length 1 

### ISSUE THREAD

**Issue by ucanfzh** [JuliaComputing/ArrayFire.jl#87]
The Julia native Array and AFArray show different behaviors when the array has a dimension of length 1. 
Not sure this are design features or things need to change. 
x=rand(AFArray{Float32},3,3) --> 3x3 AFArray{Float32,2} array
y=x[:,:,1] gives error "DimensionMismath ..." 
This works fine for native Array. 

repeat(x,outer=[1,1,2,1]) ->  3x3x2 AFArray{Float32,3} , 
but with Julia Array, one would get 3x3x2x1, four dimensional array. Auto-squeeze seems apply for AFArray. 
In both cases, the behaviors of Julia Array would be more convenient in writing "general code"
Thanks.

**Comment by ucanfzh** [comment]
It seems the array creation functions (rand, ones, constant, ...) all automatically squeeze the last dimension when its size is one. It would be better to let the user  have the option not to squeeze them.  The dimensionality of an array should be kept.
I don't find an easy way to create an uninitialized AFArray with given dimensions, like Array(::type, dim1, dim2), Array(Float32, 3, 3). Would be nice to have it. Thanks for considering.

**Comment by gaika** [comment]
fix merged with [v0.1.0](https://github.com/JuliaComputing/ArrayFire.jl/releases/tag/v0.1.0)
