### ISSUE TITLE
Error (101): Device out of memory 

### ISSUE THREAD

**Issue by ucanfzh** [JuliaComputing/ArrayFire.jl#89]
Got "out of memory" error when running the following test code 
##
import ArrayFire
x = rand(ArrayFire.AFArray{Complex{Float32}},2048, 2048)
y = 0
for m = 1:1000
y = fft(x)
info("m=$m")
mod(m,1001) == 0 && gc()
end
##
Stop at m=76. Cuda backend on Tesla C2050. 
If the number 1001 in the function mod is reduced to, say, 50, then the code seems working fine. 
It seems the gc has not run sufficiently frequent to call the finalizer of type AFArray. 
Same error also found for fftshift (via circshift?)
Thanks!

**Comment by ranjanan** [comment]
Julia's gc is non-deterministic, and does not feel the device's memory pressure unfortunately. This is a known issue, please see #27 for discussion details on this. If you find you're using device memory frequently, calling `gc()` (albeit sparingly) should help.

**Comment by ucanfzh** [comment]
Thanks.
I have tested a few other functions. It seems only those Fourier transform related functions show such an error. Surprisingly, the fft! and ifft! functions also show errors, which supposes to involve no new memory allocation. Maybe I miss some points here.

**Comment by ranjanan** [comment]
@pavanky Would you happen to know the memory consumption patterns of the in-place functions in arrayfire?

**Comment by pavanky** [comment]
@ucanfzh @ranjanan  `fft` and `ifft` are not inplace (unless you are calling `fft_inplace` and `ifft_inplace`).

Even then libraries like CUFFT and CLFFT  can and may use temporary memory during the computation process.

**Comment by ucanfzh** [comment]
@pavanky @ranjanan, Thanks! the function fft! and ifft! are indeed calling af_fft?_inplace and af_ifft?_inplace, where ?=1, 2, 3.  
Extra memory allocation for an in-place operation seems quite odd. To me, the main point of using in-place function is to allow big array that will be too large for the memory otherwise.

**Comment by pavanky** [comment]
@ucanfzh 
I just looked at your code, is `mod(m, 1001) == 0` ever evaluating to true? If not all the previously allocated memory is not freed.

@ranjanan how does `fft` call `af_fft_inplace` when it is returning an output ?

**Comment by ucanfzh** [comment]
@pavanky , you are right the code mod(m, 1001) == 0 will not be true as it is for m=1:1000. That means gc will not be trigger manually. I include that line to illustrate how often I have to call gc to avoid out of memory error. To your other question, fft! (note the bang symbol at the end) is the in-place version of fft, which call af_fft_inplace.

**Comment by pavanky** [comment]
@ucanfzh I see. But you are calling `fft` not `fft!` in the example. This creates a new array which is not garbage collected. Isn't this expected behavior ?

**Comment by ucanfzh** [comment]
@pavanky , you are right the example was for fft which was the first function that I encountered the out-of memory error. Later I notice fft!, ifft! also give the same error which is bit to my surprise.

**Comment by ranjanan** [comment]
Closing this so you can follow #27
