### ISSUE TITLE
`inv` and `det` do not support integer types

### ISSUE THREAD

**Issue by ranjanan** [JuliaComputing/ArrayFire.jl#9]
```julia
a = rand(AFArray{Int32}, 10, 10)
det(a)
inv(a)
```
Both `det` and `inv` return with a `ArrayFire Exception(202): Invalid input argument`

**Comment by pavanky** [comment]
@ranjanan none of the linear algebra functions (including matrix multiply, LU, QR, Cholesky, SVD, solve) support integer types. This is a limitation of ArrayFire.

**Comment by pavanky** [comment]
Only f32, f64, c32, c64 types are supported.

**Comment by ranjanan** [comment]
Oh okay, thanks for clarifying.

**Comment by ViralBShah** [comment]
This is the case with LAPACK too. I wouldn't worry about this for now.
