### ISSUE TITLE
Cant run ArrayFire on Windows

### ISSUE THREAD

**Issue by SamuelWiqvist** [JuliaComputing/ArrayFire.jl#90]
Hi all,

I have been trying to use ArrayFire on a Windows computer. 

However, I cannot get it work. 

I can build the ArrayFire package, but when I run the test I get:

![af_problem_pic_2_1](https://cloud.githubusercontent.com/assets/12857904/20563881/b953ec5a-b18a-11e6-9c27-f89d861dbac0.PNG)

and 

![af_problem_pic_2_2](https://cloud.githubusercontent.com/assets/12857904/20563891/c3a986d8-b18a-11e6-8810-bc975e0f012a.PNG)

When I try to use ArrayFire anyways I get the same error:

![af_problem_pic_1](https://cloud.githubusercontent.com/assets/12857904/20564108/e5810546-b18b-11e6-83b0-e6c7b2bf6db2.PNG)

ArrayFire seems to be installed correctly since I can run the c++ examples for ArrayFire, and I have also tried to update the drivers for the graphics card. I have also added the environment variable AF_PATH as AF_PATH%/lib.  But I still have the same problem. 

Any ideas on how to fix this?

**Update!**

ArrayFire apparently works when I use Julia 0.4.7:

![af_works](https://cloud.githubusercontent.com/assets/12857904/20592360/aa2c62a6-b235-11e6-8355-974c7436885a.PNG)

However I still cant get it to work in Julia 0.5.0....

Thanks!

**Comment by ranjanan** [comment]
@SamuelWiqvist I apologise for not getting to this sooner. The error you're seeing is essentially a printing error. Can you try doing `Pkg.checkout("ArrayFire")` on Julia v0.5 and see if it works for you?

**Comment by SamuelWiqvist** [comment]
@ranjanan ArrayFire now works on Julia 0.5. Thanks!
